from __future__ import annotations

import json
import os
import random
import re
import shutil
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
WEB_CODING_DEMO_ROOT = REPO_ROOT / "web_coding_demo"
if str(WEB_CODING_DEMO_ROOT) not in sys.path:
    sys.path.insert(0, str(WEB_CODING_DEMO_ROOT))

CODE_EXTS = {".html", ".htm", ".css", ".js", ".jsx", ".ts", ".tsx", ".json", ".svg"}
VIEWPORTS = [
    ("desktop", 1920, 1080),
    ("tablet", 768, 1024),
    ("mobile", 375, 812),
]
TEXT_PRD_PROMPT = """You are writing a complete implementation brief for a developer who must recreate an entire website project from scratch.
You will be shown full-page captures from every HTML page in the project, usually across desktop, tablet, and mobile layouts.

Write a detailed PRD-style instruction that is specific enough for implementation. It must describe the actual website in the inputs, not a generic website template.

What the final instruction must do:
- Cover the full project, not just the homepage.
- Explain the shared site shell first, then page-specific requirements.
- Describe information architecture, navigation, page hierarchy, hero areas, cards, lists, forms, media, CTAs, footer content, and repeated modules.
- Include interaction behavior that is visually implied, such as menus, tabs, sliders, modals, validation states, hover states, expandable sections, or user flows.
- Capture responsive differences when layout or hierarchy changes between desktop, tablet, and mobile.
- Preserve the website's visible tone, industry, audience, visual density, and content character.
- Be concrete about what appears on the page, but do not drift into CSS pixel trivia or code-level selectors.

Hard constraints:
- Do not mention screenshots, images, captures, source website, reverse engineering, benchmark datasets, or hidden implementation context.
- Do not say vague things like "build a modern website" without grounding them in the actual pages.
- Do not invent backend behavior that is not supported by visible evidence.
- If content is repeated across pages, describe the reusable pattern once and then note page-specific differences.
- If the pages contain placeholder, autogenerated, or provenance-revealing copy such as "generated page", "training project", "demo page", or similar boilerplate, do not repeat that provenance language in the final brief. Instead, describe the visible page structure and intended role in neutral product language.

Output exactly these sections:
# Project overview
# Global structure and navigation
# Page-by-page requirements
# Interaction and state requirements
# Responsive behavior
# Visual language and content details
"""
CHUNK_PROMPT = TEXT_PRD_PROMPT + """

For this batch only, do not write the final full brief yet.
Instead, extract high-signal implementation notes from the current pages only.

Requirements for the batch notes:
- Be concise but information-dense.
- Name the pages in this batch.
- List the main sections in visual order.
- Note any repeated modules, navigation patterns, form fields, content blocks, and visual motifs.
- Record only interactions that are clearly implied by the visible UI.
- Highlight responsive differences that are visible within this batch.
- Ignore obvious provenance or placeholder boilerplate if it only explains that the page is autogenerated, for training, or for demonstration. Replace that with a neutral description of the page's functional role.

Keep the same section headers as the final brief.
"""
MERGE_PROMPT = """Combine the following batch notes into one complete implementation brief for a developer.

The final brief must:
- read like a single coherent product/design specification
- cover every distinct page and shared module
- preserve concrete content, layout, and interaction details
- stay implementation-oriented without exposing source-analysis context

Do not mention batches, screenshots, images, reverse engineering, dataset names, or internal generation process.

Use exactly these sections:
# Project overview
# Global structure and navigation
# Page-by-page requirements
# Interaction and state requirements
# Responsive behavior
# Visual language and content details

Batch notes:
---
{notes}
---
"""


def maybe_load_env() -> None:
    try:
        from dotenv import load_dotenv
    except Exception:
        return
    for candidate in (REPO_ROOT / "WebCoding_Data" / ".env", REPO_ROOT / ".env"):
        if candidate.exists():
            load_dotenv(candidate)


def safe_write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def append_jsonl(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(payload, ensure_ascii=False) + "\n")


def iter_project_dirs(root: Path, limit: int = 0) -> list[Path]:
    projects = sorted(p for p in root.iterdir() if p.is_dir())
    return projects[:limit] if limit > 0 else projects


def find_html_pages(project_dir: Path) -> list[Path]:
    pages = []
    for page in sorted(project_dir.rglob("*.html")):
        rel_parts = page.relative_to(project_dir).parts
        if any(part.lower() in {"resources", "assets", "static", "node_modules"} for part in rel_parts[:-1]):
            continue
        pages.append(page)
    index = project_dir / "index.html"
    if index.exists() and index not in pages:
        pages.insert(0, index)
    return pages


def infer_page_bucket(project_dir: Path) -> str:
    return "mp" if len(find_html_pages(project_dir)) >= 4 else "sp"


def read_code_bundle(project_dir: Path) -> list[dict[str, str]]:
    code = []
    for path in sorted(project_dir.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix.lower() not in CODE_EXTS:
            continue
        rel = path.relative_to(project_dir).as_posix()
        code.append({"path": rel, "code": path.read_text("utf-8", errors="ignore")})
    return code


def collect_resources(project_dir: Path) -> list[dict[str, Any]]:
    resources = []
    for path in sorted(project_dir.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(project_dir).as_posix()
        if path.suffix.lower() in CODE_EXTS:
            continue
        kind = "image"
        if path.suffix.lower() in {".woff", ".woff2", ".ttf", ".otf", ".eot"}:
            kind = "font"
        elif path.suffix.lower() in {".mp4", ".webm"}:
            kind = "video"
        resources.append({"path": rel, "type": kind, "size_bytes": path.stat().st_size})
    return resources


def copy_project(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def write_code_bundle(code_bundle: list[dict[str, str]], out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for item in code_bundle:
        target = out_dir / item["path"]
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(item["code"], encoding="utf-8")


def write_code_bundle_from_source(source_project: Path, code_bundle: list[dict[str, str]], out_dir: Path) -> None:
    copy_project(source_project, out_dir)
    for item in code_bundle:
        target = out_dir / item["path"]
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(item["code"], encoding="utf-8")


def serialize_patch_xml(modified_files: list[dict[str, str]]) -> str:
    blocks = []
    for patch in modified_files:
        blocks.append(
            "<search>\n"
            f"{patch['search']}\n"
            "</search>\n"
            "<replace>\n"
            f"{patch['replace']}\n"
            "</replace>"
        )
    return "\n".join(blocks)


def choose_task_types(all_task_types: list[str], count: int, seed: int | None, instance_id: str) -> list[str]:
    rng = random.Random(f"{seed}:{instance_id}" if seed is not None else instance_id)
    if count > len(all_task_types):
        raise ValueError(f"Requested {count} task types, only {len(all_task_types)} available")
    return rng.sample(all_task_types, count)


def safe_name(value: str) -> str:
    value = str(value).replace(os.sep, "__")
    return re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("_") or "page"


def route_local_only(route) -> None:
    url = route.request.url
    if url.startswith(("file://", "data:", "blob:")):
        route.continue_()
    else:
        route.abort("connectionfailed")


def screenshot_project_to_dir(project_dir: Path, out_dir: Path) -> list[dict[str, str]]:
    from playwright.sync_api import sync_playwright

    pages = find_html_pages(project_dir)
    if not pages:
        raise RuntimeError("no html pages found")
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, str]] = []
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        for html in pages:
            rel = html.relative_to(project_dir).as_posix()
            page_key = safe_name(rel[:-5] if rel.lower().endswith(".html") else rel)
            for vp_name, width, height in VIEWPORTS:
                page = browser.new_page(viewport={"width": width, "height": height})
                page.route("**/*", route_local_only)
                try:
                    page.goto("file://" + str(html.resolve()), wait_until="domcontentloaded", timeout=20000)
                    page.wait_for_timeout(1000)
                    dest = out_dir / f"{page_key}__{vp_name}.jpg"
                    page.screenshot(path=str(dest), full_page=True, type="jpeg", quality=82, timeout=90000)
                    records.append({"page": rel, "viewport": vp_name, "path": dest.relative_to(out_dir.parent).as_posix()})
                finally:
                    page.close()
        browser.close()
    return records


def record_project_to_dir(project_dir: Path, out_dir: Path) -> list[dict[str, Any]]:
    from playwright.sync_api import sync_playwright

    pages = find_html_pages(project_dir)
    if not pages:
        raise RuntimeError("no html pages found")
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, Any]] = []
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        for html in pages:
            rel = html.relative_to(project_dir).as_posix()
            page_key = safe_name(rel[:-5] if rel.lower().endswith(".html") else rel)
            record_dir = out_dir / f"{page_key}_recording"
            record_dir.mkdir(parents=True, exist_ok=True)
            context = browser.new_context(
                viewport={"width": 1280, "height": 720},
                record_video_dir=str(record_dir),
                record_video_size={"width": 1280, "height": 720},
            )
            page = context.new_page()
            page.route("**/*", route_local_only)
            try:
                page.goto("file://" + str(html.resolve()), wait_until="domcontentloaded", timeout=30000)
                page.wait_for_timeout(1500)

                # Use human-like interaction instead of mechanical scrolling
                from WebCoding_Data.construct.human_like_playwright_record import HumanRecorder, run_story

                recorder = HumanRecorder(page, record_dir, time.time())
                run_story(page, recorder)
                recorder.pause(800, 1200, "final_pause")
            finally:
                video = page.video
                context.close()
                if video:
                    raw_video = Path(video.path())
                    if raw_video.exists():
                        final = out_dir / f"{page_key}.webm"
                        if final.exists():
                            final.unlink()
                        shutil.move(str(raw_video), final)
                        records.append({"page": rel, "path": final.relative_to(out_dir.parent).as_posix()})
                shutil.rmtree(record_dir, ignore_errors=True)
        browser.close()
    return records


def encode_image_for_api(path: Path, max_width: int = 1200, max_bytes: int = 3_500_000) -> str:
    import base64
    from PIL import Image

    img = Image.open(path).convert("RGB")
    if img.width > max_width:
        ratio = max_width / img.width
        img = img.resize((max_width, max(1, int(img.height * ratio))))

    tmp = Path(str(path) + ".api.jpg")
    quality = 82
    while True:
        img.save(tmp, "JPEG", quality=quality, optimize=True)
        if tmp.stat().st_size <= max_bytes or quality <= 50:
            data = tmp.read_bytes()
            tmp.unlink(missing_ok=True)
            return base64.b64encode(data).decode("utf-8")
        quality -= 8


def call_vlm(model: str, prompt: str, image_paths: list[Path] | None = None, max_tokens: int = 4096) -> str:
    from openai import OpenAI

    maybe_load_env()
    api_key, base_url, _ = ensure_api_env(prefer_vision=True)
    client = OpenAI(api_key=api_key, base_url=base_url, timeout=180.0)
    if image_paths:
        content: list[dict[str, Any]] = [{"type": "text", "text": prompt}]
        for image_path in image_paths:
            b64 = encode_image_for_api(image_path)
            content.append({"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{b64}"}})
        messages = [{"role": "user", "content": content}]
    else:
        messages = [{"role": "user", "content": prompt}]
    response = client.chat.completions.create(model=model, messages=messages, max_tokens=max_tokens)
    return response.choices[0].message.content or ""


def generate_prd(project_dir: Path, screenshots_dir: Path) -> tuple[str, list[dict[str, str]]]:
    maybe_load_env()
    _, _, model = ensure_api_env(prefer_vision=True)
    screenshots = screenshot_project_to_dir(project_dir, screenshots_dir)
    paths = [screenshots_dir.parent / shot["path"] for shot in screenshots]
    notes: list[str] = []
    chunk_size = 4
    for start in range(0, len(paths), chunk_size):
        chunk = paths[start : start + chunk_size]
        labels = "\n".join(
            f"- {screenshots[idx]['page']} ({screenshots[idx]['viewport']})"
            for idx in range(start, min(start + chunk_size, len(paths)))
        )
        prompt = CHUNK_PROMPT + "\n\nPages in this batch:\n" + labels
        notes.append(call_vlm(model, prompt, chunk, max_tokens=1600))
    instruction = notes[0] if len(notes) == 1 else call_vlm(model, MERGE_PROMPT.format(notes="\n\n".join(notes)), None, max_tokens=3200)
    return instruction, screenshots


def description_to_text(description: Any) -> str:
    if isinstance(description, str):
        return description.strip()
    if isinstance(description, list):
        lines = []
        for item in description:
            if isinstance(item, dict):
                task_type = str(item.get("task_type", "")).strip()
                desc = str(item.get("description", "")).strip()
                if task_type and desc:
                    lines.append(f"[{task_type}] {desc}")
                elif desc:
                    lines.append(desc)
            elif item:
                lines.append(str(item).strip())
        return "\n".join(line for line in lines if line)
    return str(description or "").strip()


def base_info(instance_id: str, task: str, task_family: str) -> dict[str, Any]:
    return {
        "instance_id": instance_id,
        "task": task,
        "task_family": task_family,
        "task_type": [],
        "description": "",
        "instruction": "",
        "src_code": [],
        "dst_code": [],
        "src_screenshot": [],
        "dst_screenshot": [],
        "input_screenshots": [],
        "input_videos": [],
        "label_modified_files": [],
        "resources": [],
        "meta": {},
    }


def ensure_api_env(prefer_vision: bool = False) -> tuple[str, str | None, str]:
    maybe_load_env()
    if prefer_vision:
        api_key = os.environ.get("VISION_OPENAI_API_KEY") or os.environ.get("OPENAI_API_KEY")
        base_url = os.environ.get("VISION_OPENAI_BASE_URL") or os.environ.get("OPENAI_BASE_URL")
        model = os.environ.get("VISION_MODEL") or os.environ.get("OPENAI_MODEL") or os.environ.get("MODEL") or "gpt-4o"
    else:
        api_key = os.environ.get("OPENAI_API_KEY") or os.environ.get("VISION_OPENAI_API_KEY")
        base_url = os.environ.get("OPENAI_BASE_URL") or os.environ.get("VISION_OPENAI_BASE_URL")
        model = os.environ.get("OPENAI_MODEL") or os.environ.get("MODEL") or "gpt-4o"
    if not api_key:
        raise ValueError("Missing API key in environment")
    return api_key, base_url, model


def write_generation_instance(
    output_root: Path,
    task: str,
    project_dir: Path,
    info: dict[str, Any],
) -> Path:
    instance_dir = output_root / project_dir.name
    if instance_dir.exists():
        shutil.rmtree(instance_dir)
    instance_dir.mkdir(parents=True, exist_ok=True)
    copy_project(project_dir, instance_dir / "dst")
    safe_write_json(instance_dir / "info.json", info)
    return instance_dir


def write_pair_instance(
    output_root: Path,
    bucket: str,
    project_dir: Path,
    src_code: list[dict[str, str]],
    dst_code: list[dict[str, str]],
    info: dict[str, Any],
) -> Path:
    instance_dir = output_root / bucket / project_dir.name
    if instance_dir.exists():
        shutil.rmtree(instance_dir)
    instance_dir.mkdir(parents=True, exist_ok=True)
    write_code_bundle_from_source(project_dir, src_code, instance_dir / "src")
    write_code_bundle_from_source(project_dir, dst_code, instance_dir / "dst")
    safe_write_json(instance_dir / "info.json", info)
    return instance_dir


def build_generation_data(project_dir: Path) -> dict[str, Any]:
    return {
        "instance_id": project_dir.name,
        "dst_code": read_code_bundle(project_dir),
        "resources": collect_resources(project_dir),
    }


def load_edit_catalog() -> tuple[list[str], dict[str, str]]:
    from web_coding_demo.synthetic.edit import FORWARD_TASKS, TASK_DESCRIPTIONS

    return list(FORWARD_TASKS), dict(TASK_DESCRIPTIONS)


def load_repair_catalog() -> tuple[list[str], dict[str, str]]:
    from web_coding_demo.synthetic.repair import DEFECT_TYPES, DEFECT_DESCRIPTIONS

    return list(DEFECT_TYPES), dict(DEFECT_DESCRIPTIONS)


def build_forward_edit_synthesizer(api_key: str, base_url: str | None, model: str, max_retries: int = 3):
    from web_coding_demo.synthetic.synthesizer import BaseSynthesizer

    _, task_descriptions = load_edit_catalog()

    class ForwardEditPairSynthesizer(BaseSynthesizer):
        def generate_forward_pair(self, generation_data: dict[str, Any], task_types: list[str]) -> dict[str, Any]:
            src_code = generation_data["dst_code"]
            src_code_context = self.format_code_context(src_code)
            task_descriptions_str = ""
            for idx, task_type in enumerate(task_types, 1):
                task_descriptions_str += f"Task {idx}: {task_type}\n  Guideline: {task_descriptions[task_type]}\n\n"
            task_types_json = json.dumps(task_types, ensure_ascii=False)
            prompt = f"""You are an expert web developer creating high-quality web editing benchmark pairs.

I have an existing webpage codebase. Based on this code, generate {len(task_types)} context-aware editing request(s), and then implement all requested edits using strict search/replace blocks.

Tasks to implement:
{task_descriptions_str}

IMPORTANT GUIDELINES:
1. Each request must fit the website's existing theme, structure, and assets.
2. The request must describe user-facing behavior and visible outcomes, not low-level implementation details.
3. The edits must be substantial but realistic for the current repository.
4. Do not invent missing pages or external services that the current project cannot support.
5. The search text must come exactly from the current code and match uniquely.

Return XML with:
<description>
[
  {{"task_type": "ExactTaskType", "description": "Concrete editing request"}}
]
</description>
<search_replace path="path/to/file">
<search>
exact source text
</search>
<replace>
edited target text
</replace>
</search_replace>

**CRITICAL - task_type MUST be EXACTLY one of these values (copy verbatim):**
{task_types_json}

Here is the existing source code to edit:
{src_code_context}"""

            result = self._generate_and_apply_with_retry(
                messages=[
                    {
                        "role": "system",
                        "content": "You generate web editing benchmark pairs in XML using exact search/replace edits.",
                    },
                    {"role": "user", "content": prompt},
                ],
                code_list=src_code,
                max_retries=self.max_retries,
                expected_task_types=task_types,
            )
            return {
                "task": "edit",
                "task_type": task_types,
                "description": result["description"],
                "src_code": src_code,
                "dst_code": result["modified_code"],
                "resources": generation_data.get("resources", []),
                "label_modified_files": result.get("modified_files", []),
                "synthetic_modified_files": result.get("modified_files", []),
                "llm_raw_response": result.get("raw_response"),
                "llm_metadata": result.get("llm_metadata"),
            }

        def process_single_generation_entry(self, *args, **kwargs) -> list[dict[str, Any]]:
            raise NotImplementedError

    return ForwardEditPairSynthesizer(api_key, base_url, model, max_tokens=64 * 1024, max_retries=max_retries)


def build_repair_synthesizer(api_key: str, base_url: str | None, model: str, max_retries: int = 3):
    from web_coding_demo.synthetic.repair import RepairTaskSynthesizer

    return RepairTaskSynthesizer(api_key, base_url, model, max_tokens=64 * 1024, max_retries=max_retries)
