from __future__ import annotations

import json
import os
import random
import re
import shutil
import time
from collections import Counter
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]

CODE_EXTS = {".html", ".htm", ".css", ".js", ".jsx", ".ts", ".tsx", ".json", ".svg"}
TRAIN_CODE_EXTS = {".html", ".htm", ".css", ".js", ".jsx", ".ts", ".tsx"}
PROVENANCE_FILES = {"metadata.json", "original_webcode2m_screenshot.png"}
REMOTE_URL_RE = re.compile(r"https?://[^\s\"'<>)]*", re.I)
SVG_NAMESPACE_URLS = {
    "http://www.w3.org/2000/svg",
    "http://www.w3.org/1999/xlink",
    "http://purl.org/dc/elements/1.1/",
    "http://creativecommons.org/ns#",
    "http://www.inkscape.org/namespaces/inkscape",
    "http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd",
    "http://www.serif.com/",
}
VIEWPORTS = [
    ("desktop", 1920, 1080),
    ("tablet", 768, 1024),
    ("mobile", 375, 812),
]
TEXT_PRD_PROMPT = """You are writing a complete implementation brief for a developer who must recreate an entire website project from scratch.
You will be shown full-page captures from every HTML page in the project. Each page is captured at three viewports — desktop (1920×1080), tablet (768×1024), and mobile (375×812) — so three consecutive images of the same page show the same content at different screen widths, NOT different pages.

Write a detailed PRD-style instruction that is specific enough for implementation. It must describe the actual website in the inputs, not a generic website template.

What the final instruction must do:
- Cover the full project, not just the homepage.
- Explain the shared site shell first, then page-specific requirements.
- Describe information architecture, navigation, page hierarchy, hero areas, cards, lists, forms, media, CTAs, footer content, and repeated modules.
- Include interaction behavior that is visually implied, such as menus, tabs, sliders, modals, validation states, hover states, expandable sections, or user flows.
- Capture responsive differences when layout or hierarchy changes between desktop, tablet, and mobile.
- Preserve the website's visible tone, industry, audience, visual density, and content character.
- Be concrete about what appears on the page, but do not drift into CSS pixel trivia or code-level selectors.

Hard constraints:
- Do not mention screenshots, images, captures, source website, reverse engineering, benchmark datasets, or hidden implementation context.
- Do not say vague things like "build a modern website" without grounding them in the actual pages.
- Do not invent backend behavior that is not supported by visible evidence.
- If content is repeated across pages, describe the reusable pattern once and then note page-specific differences.
- If the pages contain placeholder, autogenerated, or provenance-revealing copy such as "generated page", "training project", "demo page", or similar boilerplate, do not repeat that provenance language in the final brief. Instead, describe the visible page structure and intended role in neutral product language.
- If any images appear broken, missing, or show as empty boxes, describe the image slot's role and approximate dimensions, but do not call them "placeholders", "broken", or "missing". Treat every visible image slot as an intentional part of the design.

Output exactly these sections:
# Project overview
# Global structure and navigation
# Page-by-page requirements
# Interaction and state requirements
# Responsive behavior
# Visual language and content details
"""
CHUNK_PROMPT = TEXT_PRD_PROMPT + """

For this batch only, do not write the final full brief yet.
Instead, extract high-signal implementation notes from the current pages only.

Requirements for the batch notes:
- Be concise but information-dense.
- Name the pages in this batch.
- List the main sections in visual order.
- Note any repeated modules, navigation patterns, form fields, content blocks, and visual motifs.
- Record only interactions that are clearly implied by the visible UI.
- Highlight responsive differences that are visible within this batch.
- Ignore obvious provenance or placeholder boilerplate if it only explains that the page is autogenerated, for training, or for demonstration. Replace that with a neutral description of the page's functional role.

Keep the same section headers as the final brief.
"""
MERGE_PROMPT = """Combine the following batch notes into one complete implementation brief for a developer.

The final brief must:
- read like a single coherent product/design specification
- cover every distinct page and shared module
- preserve concrete content, layout, and interaction details
- stay implementation-oriented without exposing source-analysis context

Do not mention batches, screenshots, images, reverse engineering, dataset names, or internal generation process.

Use exactly these sections:
# Project overview
# Global structure and navigation
# Page-by-page requirements
# Interaction and state requirements
# Responsive behavior
# Visual language and content details

Batch notes:
---
{notes}
---
"""


def maybe_load_env() -> None:
    try:
        from dotenv import load_dotenv
    except Exception:
        return
    for candidate in (REPO_ROOT / ".env",):
        if candidate.exists():
            load_dotenv(candidate)


def safe_write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def append_jsonl(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(payload, ensure_ascii=False) + "\n")


def iter_project_dirs(root: Path, limit: int = 0) -> list[Path]:
    projects = sorted(p for p in root.iterdir() if p.is_dir())
    return projects[:limit] if limit > 0 else projects


def find_html_pages(project_dir: Path) -> list[Path]:
    pages = []
    for page in sorted(project_dir.rglob("*.html")):
        rel_parts = page.relative_to(project_dir).parts
        if any(part.lower() in {"resources", "assets", "static", "node_modules"} for part in rel_parts[:-1]):
            continue
        pages.append(page)
    index = project_dir / "index.html"
    if index.exists() and index not in pages:
        pages.insert(0, index)
    return pages


def infer_page_bucket(project_dir: Path) -> str:
    return "mp" if len(find_html_pages(project_dir)) >= 2 else "sp"


def read_code_bundle(project_dir: Path, code_only: bool = False) -> list[dict[str, str]]:
    """Read code files from project. code_only=True excludes .svg/.json (for training data)."""
    exts = TRAIN_CODE_EXTS if code_only else CODE_EXTS
    code = []
    for path in sorted(project_dir.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix.lower() not in exts:
            continue
        rel = path.relative_to(project_dir).as_posix()
        if rel in PROVENANCE_FILES:
            continue
        code.append({"path": rel, "code": sanitize_render_text(path.read_text("utf-8", errors="ignore"))})
    return code


def collect_resources(project_dir: Path) -> list[dict[str, Any]]:
    resources = []
    for path in sorted(project_dir.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(project_dir).as_posix()
        if rel in PROVENANCE_FILES:
            continue
        if path.suffix.lower() in CODE_EXTS:
            continue
        kind = "image"
        if path.suffix.lower() in {".woff", ".woff2", ".ttf", ".otf", ".eot"}:
            kind = "font"
        elif path.suffix.lower() in {".mp4", ".webm"}:
            kind = "video"
        resources.append({"type": kind, "path": rel, "description": "", "size_bytes": path.stat().st_size})
    return resources


def build_file_manifest(project_dir: Path) -> list[dict[str, Any]]:
    """List all files with type classification and size (for training data context)."""
    manifest = []
    for path in sorted(project_dir.rglob("*")):
        if not path.is_file():
            continue
        if path.name in PROVENANCE_FILES:
            continue
        rel = path.relative_to(project_dir).as_posix()
        suffix = path.suffix.lower()
        if suffix in TRAIN_CODE_EXTS:
            ftype = "code"
        elif suffix in {".svg", ".json"}:
            ftype = "asset"
        elif suffix in {".woff", ".woff2", ".ttf", ".otf", ".eot"}:
            ftype = "font"
        elif suffix in {".mp4", ".webm"}:
            ftype = "video"
        else:
            ftype = "image"
        manifest.append({"path": rel, "type": ftype, "size_bytes": path.stat().st_size})
    return manifest


def copy_project(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns(*PROVENANCE_FILES))
    sanitize_project_files(dst)


def sanitize_render_text(text: str) -> str:
    def replace_url(match: re.Match[str]) -> str:
        url = match.group(0)
        if url in SVG_NAMESPACE_URLS:
            return url
        # Keep picsum.photos fallback URLs (injected by clean step)
        if "picsum.photos" in url:
            return url
        return "#"

    def replace_css_url(match: re.Match[str]) -> str:
        if "picsum.photos" in match.group(0):
            return match.group(0)
        return 'url("")'

    text = re.sub(r"url\(\s*(['\"]?)https?://[^'\"\)]*\1\s*\)", replace_css_url, text, flags=re.I)
    text = re.sub(r"@import\s+(['\"])https?://[^'\"]*\1\s*;?", "", text, flags=re.I)
    return REMOTE_URL_RE.sub(replace_url, text)


def sanitize_project_files(project_dir: Path) -> None:
    for path in project_dir.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in (CODE_EXTS - {".json"}):
            continue
        text = path.read_text("utf-8", errors="ignore")
        sanitized = sanitize_render_text(text)
        if sanitized != text:
            path.write_text(sanitized, encoding="utf-8")


def write_code_bundle(code_bundle: list[dict[str, str]], out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for item in code_bundle:
        target = out_dir / item["path"]
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(item["code"], encoding="utf-8")


def write_code_bundle_from_source(source_project: Path, code_bundle: list[dict[str, str]], out_dir: Path) -> None:
    copy_project(source_project, out_dir)
    for item in code_bundle:
        target = out_dir / item["path"]
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(item["code"], encoding="utf-8")


def serialize_patch_xml(modified_files: list[dict[str, str]]) -> str:
    blocks = []
    for patch in modified_files:
        blocks.append(
            "<search>\n"
            f"{patch['search']}\n"
            "</search>\n"
            "<replace>\n"
            f"{patch['replace']}\n"
            "</replace>"
        )
    return "\n".join(blocks)


def choose_task_types(
    all_task_types: list[str],
    count: int | tuple[int, int],
    seed: int | None,
    instance_id: str,
    allow_repeat: bool = False,
) -> list[str]:
    """Select task types for an instance.

    count: either a fixed int or (min, max) tuple for random range.
    allow_repeat: if True, use choices (with replacement) instead of sample.
        Needed for repair tasks where type pool (11) < max count (12).
    """
    rng = random.Random(f"{seed}:{instance_id}" if seed is not None else instance_id)
    if isinstance(count, tuple):
        min_c, max_c = count
        if not allow_repeat:
            max_c = min(max_c, len(all_task_types))
        n = rng.randint(min_c, max_c)
    else:
        n = count
    if allow_repeat:
        return rng.choices(all_task_types, k=n)
    if n > len(all_task_types):
        raise ValueError(f"Requested {n} task types, only {len(all_task_types)} available")
    return rng.sample(all_task_types, n)


def safe_name(value: str) -> str:
    value = str(value).replace(os.sep, "__")
    return re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("_") or "page"


def route_local_only(route) -> None:
    url = route.request.url
    if url.startswith(("file://", "data:", "blob:")) or "picsum.photos" in url:
        route.continue_()
    else:
        route.abort("connectionfailed")


def screenshot_project_to_dir(project_dir: Path, out_dir: Path) -> list[dict[str, str]]:
    from playwright.sync_api import sync_playwright

    pages = find_html_pages(project_dir)
    if not pages:
        raise RuntimeError("no html pages found")
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, str]] = []
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        try:
            for html in pages:
                rel = html.relative_to(project_dir).as_posix()
                page_key = safe_name(rel[:-5] if rel.lower().endswith(".html") else rel)
                for vp_name, width, height in VIEWPORTS:
                    page = browser.new_page(viewport={"width": width, "height": height})
                    page.route("**/*", route_local_only)
                    try:
                        page.goto("file://" + str(html.resolve()), wait_until="domcontentloaded", timeout=20000)
                        page.wait_for_timeout(1000)
                        dest = out_dir / f"{page_key}__{vp_name}.jpg"
                        page.screenshot(path=str(dest), full_page=True, type="jpeg", quality=82, timeout=90000)
                        records.append({"page": rel, "viewport": vp_name, "path": dest.relative_to(out_dir.parent).as_posix()})
                    except Exception as exc:
                        print(f"  screenshot failed for {rel} ({vp_name}): {exc}")
                    finally:
                        page.close()
        finally:
            browser.close()
    return records


def record_project_to_dir(project_dir: Path, out_dir: Path) -> list[dict[str, Any]]:
    from playwright.sync_api import sync_playwright

    pages = find_html_pages(project_dir)
    if not pages:
        raise RuntimeError("no html pages found")
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, Any]] = []
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        try:
            for html in pages:
                rel = html.relative_to(project_dir).as_posix()
                page_key = safe_name(rel[:-5] if rel.lower().endswith(".html") else rel)
                record_dir = out_dir / f"{page_key}_recording"
                record_dir.mkdir(parents=True, exist_ok=True)
                context = browser.new_context(
                    viewport={"width": 1280, "height": 720},
                    record_video_dir=str(record_dir),
                    record_video_size={"width": 1280, "height": 720},
                )
                page = context.new_page()
                page.route("**/*", route_local_only)
                try:
                    page.goto("file://" + str(html.resolve()), wait_until="domcontentloaded", timeout=30000)
                    page.wait_for_timeout(1500)

                    # Use human-like interaction instead of mechanical scrolling
                    from WebCoding_Data.construct.human_like_playwright_record import HumanRecorder, run_story

                    recorder = HumanRecorder(page, record_dir, time.time())
                    run_story(page, recorder)
                    recorder.pause(800, 1200, "final_pause")
                except Exception as exc:
                    print(f"  recording failed for {rel}: {exc}")
                finally:
                    video = page.video
                    context.close()
                    if video:
                        raw_video = Path(video.path())
                        if raw_video.exists():
                            final = out_dir / f"{page_key}.webm"
                            if final.exists():
                                final.unlink()
                            shutil.move(str(raw_video), final)
                            records.append({"page": rel, "path": final.relative_to(out_dir.parent).as_posix()})
                    shutil.rmtree(record_dir, ignore_errors=True)
        finally:
            browser.close()
    return records


def encode_image_for_api(path: Path, max_width: int = 1200, max_bytes: int = 3_500_000) -> str:
    import base64
    import tempfile
    from PIL import Image

    img = Image.open(path).convert("RGB")
    if img.width > max_width:
        ratio = max_width / img.width
        img = img.resize((max_width, max(1, int(img.height * ratio))))

    quality = 82
    while True:
        with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as tmp_f:
            tmp = Path(tmp_f.name)
        try:
            img.save(tmp, "JPEG", quality=quality, optimize=True)
            if tmp.stat().st_size <= max_bytes or quality <= 50:
                data = tmp.read_bytes()
                return base64.b64encode(data).decode("utf-8")
        finally:
            tmp.unlink(missing_ok=True)
        quality -= 8


_VLM_RETRY_DELAYS = [10, 30, 60]


def call_vlm(model: str, prompt: str, image_paths: list[Path] | None = None, max_tokens: int = 4096) -> str:
    """Call VLM with exponential-backoff retry on transient errors."""
    from openai import OpenAI

    maybe_load_env()
    api_key, base_url, _ = ensure_api_env(prefer_vision=True)
    client = OpenAI(api_key=api_key, base_url=base_url, timeout=180.0)
    if image_paths:
        content: list[dict[str, Any]] = [{"type": "text", "text": prompt}]
        use_qwen37_image = model.lower() == "qwen3.7-max"
        for image_path in image_paths:
            b64 = encode_image_for_api(image_path)
            data_url = f"data:image/jpeg;base64,{b64}"
            if use_qwen37_image:
                content.append({"type": "image", "image": data_url})
            else:
                content.append({"type": "image_url", "image_url": {"url": data_url}})
        messages = [{"role": "user", "content": content}]
    else:
        messages = [{"role": "user", "content": prompt}]

    last_error: Exception | None = None
    for attempt in range(1 + len(_VLM_RETRY_DELAYS)):
        try:
            response = client.chat.completions.create(model=model, messages=messages, max_tokens=max_tokens)
            return response.choices[0].message.content or ""
        except Exception as e:
            last_error = e
            err_lower = str(e).lower()
            if any(kw in err_lower for kw in ["invalid api key", "authentication", "model not found"]):
                raise  # non-retryable
            if attempt < len(_VLM_RETRY_DELAYS):
                delay = _VLM_RETRY_DELAYS[attempt]
                print(f"  VLM error (attempt {attempt+1}): {e} — retrying in {delay}s")
                time.sleep(delay)
    raise last_error  # type: ignore[misc]


def _truncate_text(value: str, limit: int) -> str:
    if len(value) <= limit:
        return value
    return value[:limit] + "\n<!-- truncated for PRD synthesis -->"


def code_context_for_prd(project_dir: Path, page_names: set[str] | None = None, max_chars: int = 18000) -> str:
    """Build a compact source context so PRDs are grounded in code and screenshots."""
    code_items = read_code_bundle(project_dir)
    selected: list[dict[str, str]] = []
    page_names = page_names or set()
    for item in code_items:
        path = item["path"]
        suffix = Path(path).suffix.lower()
        if path in page_names or suffix in {".css", ".js", ".jsx", ".ts", ".tsx"}:
            selected.append(item)
    if not selected:
        selected = code_items[:8]

    chunks: list[str] = []
    remaining = max_chars
    for item in selected:
        if remaining <= 0:
            break
        code = _truncate_text(item["code"], min(remaining, 5000))
        chunks.append(f'<file path="{item["path"]}">\n{code}\n</file>')
        remaining -= len(code)
    return "<source_context>\n" + "\n".join(chunks) + "\n</source_context>"


def generate_prd(project_dir: Path, screenshots_dir: Path) -> tuple[str, list[dict[str, str]]]:
    maybe_load_env()
    _, _, model = ensure_api_env(prefer_vision=True)
    screenshots = screenshot_project_to_dir(project_dir, screenshots_dir)
    paths = [screenshots_dir.parent / shot["path"] for shot in screenshots]
    notes: list[str] = []
    chunk_size = 4
    for start in range(0, len(paths), chunk_size):
        chunk = paths[start : start + chunk_size]
        # Group labels by page so VLM sees "page: desktop, tablet, mobile viewports"
        # instead of three separate lines that could be mistaken for different pages.
        grouped: dict[str, list[str]] = {}
        for idx in range(start, min(start + chunk_size, len(paths))):
            page = screenshots[idx]["page"]
            vp = screenshots[idx]["viewport"]
            grouped.setdefault(page, []).append(vp)
        labels = "\n".join(
            f"- {page}: {', '.join(vps)} viewports (same page, different screen widths)"
            for page, vps in grouped.items()
        )
        page_names = {screenshots[idx]["page"] for idx in range(start, min(start + chunk_size, len(paths)))}
        source_context = code_context_for_prd(project_dir, page_names)
        prompt = (
            CHUNK_PROMPT
            + "\n\nPages in this batch:\n"
            + labels
            + "\n\nUse these source files together with the screenshots. The final notes must be grounded in both visual evidence and implementation structure:\n"
            + source_context
        )
        notes.append(call_vlm(model, prompt, chunk, max_tokens=1600))
    merge_source_context = code_context_for_prd(project_dir, None, max_chars=22000)
    instruction = (
        notes[0]
        if len(notes) == 1
        else call_vlm(
            model,
            MERGE_PROMPT.format(notes="\n\n".join(notes))
            + "\n\nUse this compact source context to resolve ambiguities and keep the PRD implementation-grounded:\n"
            + merge_source_context,
            None,
            max_tokens=3200,
        )
    )
    return instruction, screenshots


def description_to_text(description: Any) -> str:
    if isinstance(description, str):
        return description.strip()
    if isinstance(description, list):
        lines = []
        for item in description:
            if isinstance(item, dict):
                task_type = str(item.get("task_type", "")).strip()
                desc = str(item.get("description", "")).strip()
                if task_type and desc:
                    lines.append(f"[{task_type}] {desc}")
                elif desc:
                    lines.append(desc)
            elif item:
                lines.append(str(item).strip())
        return "\n".join(line for line in lines if line)
    return str(description or "").strip()


def base_info(instance_id: str, task: str) -> dict[str, Any]:
    return {
        "instance_id": instance_id,
        "task": task,
        "task_type": [],
        "description": [],
        "src_code": [],
        "dst_code": [],
        "file_manifest": [],
        "src_screenshot": [],
        "dst_screenshot": [],
        "label_modified_files": [],
        "resources": [],
        "meta": {},
    }


def ensure_api_env(prefer_vision: bool = False) -> tuple[str, str | None, str]:
    maybe_load_env()
    if prefer_vision:
        api_key = os.environ.get("VISION_OPENAI_API_KEY") or os.environ.get("OPENAI_API_KEY")
        base_url = os.environ.get("VISION_OPENAI_BASE_URL") or os.environ.get("OPENAI_BASE_URL")
        model = os.environ.get("VISION_MODEL") or os.environ.get("OPENAI_MODEL") or os.environ.get("MODEL") or "gpt-4o"
    else:
        api_key = os.environ.get("OPENAI_API_KEY") or os.environ.get("VISION_OPENAI_API_KEY")
        base_url = os.environ.get("OPENAI_BASE_URL") or os.environ.get("VISION_OPENAI_BASE_URL")
        model = os.environ.get("OPENAI_MODEL") or os.environ.get("MODEL") or "gpt-4o"
    if not api_key:
        raise ValueError("Missing API key in environment")
    return api_key, base_url, model


def write_generation_instance(
    output_root: Path,
    task: str,
    project_dir: Path,
    info: dict[str, Any],
) -> Path:
    instance_dir = output_root / project_dir.name
    if instance_dir.exists():
        shutil.rmtree(instance_dir)
    instance_dir.mkdir(parents=True, exist_ok=True)
    copy_project(project_dir, instance_dir / "dst")
    safe_write_json(instance_dir / "info.json", info)
    return instance_dir


def write_pair_instance(
    output_root: Path,
    bucket: str,
    project_dir: Path,
    src_code: list[dict[str, str]],
    dst_code: list[dict[str, str]],
    info: dict[str, Any],
) -> Path:
    instance_dir = output_root / bucket / project_dir.name
    if instance_dir.exists():
        shutil.rmtree(instance_dir)
    instance_dir.mkdir(parents=True, exist_ok=True)
    write_code_bundle_from_source(project_dir, src_code, instance_dir / "src")
    write_code_bundle_from_source(project_dir, dst_code, instance_dir / "dst")
    safe_write_json(instance_dir / "info.json", info)
    return instance_dir


def build_generation_data(project_dir: Path) -> dict[str, Any]:
    return {
        "instance_id": project_dir.name,
        "dst_code": read_code_bundle(project_dir),
        "resources": collect_resources(project_dir),
    }




def strip_markdown_fence(response_text: str) -> str:
    if "```xml" in response_text:
        return response_text.split("```xml", 1)[1].split("```", 1)[0].strip()
    if "```json" in response_text:
        return response_text.split("```json", 1)[1].split("```", 1)[0].strip()
    if "```" not in response_text:
        return response_text
    parts = response_text.split("```")
    if len(parts) < 3:
        return response_text
    fenced = parts[1].strip()
    for lang in ("xml", "XML", "json", "JSON"):
        if fenced.startswith(lang):
            return fenced[len(lang) :].strip()
    return fenced


_EDIT_TASKS: list[str] = [
    "Data Table",
    "Rich Text Editor",
    "Drag & Drop Interface",
    "Tree View",
    "Real-time Dashboard",
    "Infinite Scroll",
    "Async Form Validation",
    "File Upload with Progress",
    "Parallax Scrolling",
    "Page Transitions",
    "Particle Effects",
    "Skeleton Loading",
    "Shopping Cart",
    "User Authentication",
    "Multi-step Wizard",
    "Notification Center",
    "Dark Mode Toggle",
    "Accordion",
    "Modal Dialog",
    "Tooltip",
    "Breadcrumb Navigation",
    "Tabs",
    "Toast Notifications",
    "Star Rating",
    "Copy to Clipboard",
    "Back to Top",
    "Cookie Consent",
    "Responsive Navigation",
    "Sticky Header",
    "Search Autocomplete",
    "Image Lightbox",
    "Countdown Timer",
    "Color Picker",
    "Date Picker",
    "Carousel",
    "Keyboard Shortcuts",
    "Context Menu",
    "Lazy Loading Images",
    "Print Stylesheet",
    "Undo Redo",
]

_EDIT_TASK_DESCRIPTIONS: dict[str, str] = {
    "Data Table": "Implement an advanced data table component with rich functionality.\n    Requirements:\n    - Display tabular data with sortable columns (click header to sort asc/desc).\n    - Add pagination controls (previous/next, page numbers, items per page selector).\n    - Implement column filtering with dropdown or text input per column.\n    - Support row selection with checkboxes (single and select-all).\n    - Add inline editing capability for editable cells.\n    - Responsive design: horizontal scroll or card view on mobile.",
    "Rich Text Editor": "Implement a WYSIWYG rich text editor component.\n    Requirements:\n    - Create a toolbar with formatting buttons (Bold, Italic, Underline, Strikethrough).\n    - Support heading levels (H1-H3), lists (ordered/unordered), and blockquotes.\n    - Implement link insertion with URL input dialog.\n    - Add image embedding via URL or placeholder.\n    - Use contenteditable div or textarea with preview mode.\n    - Sync formatted content to a hidden textarea for form submission.",
    "Drag & Drop Interface": "Implement a drag-and-drop interface for reordering or organizing items.\n    Requirements:\n    - Create draggable items with visual drag handles.\n    - Implement drop zones with visual feedback (highlight on dragover).\n    - Support reordering within a single list (Kanban column style).\n    - Add cross-container drag support if multiple lists exist.\n    - Show placeholder/ghost element during drag operation.\n    - Persist order changes to data structure and optionally localStorage.",
    "Tree View": "Implement a hierarchical tree view component for nested data.\n    Requirements:\n    - Display nested items with expand/collapse toggles (arrows or +/- icons).\n    - Support multiple levels of nesting (at least 3 levels deep).\n    - Implement lazy loading or virtual rendering for large trees.\n    - Add checkbox selection with parent-child cascade (select parent selects all children).\n    - Support keyboard navigation (arrow keys, Enter to toggle).\n    - Add search/filter functionality to highlight matching nodes.",
    "Real-time Dashboard": "Implement a real-time dashboard with live-updating metrics.\n    Requirements:\n    - Create dashboard cards displaying key metrics (numbers, percentages).\n    - Simulate real-time data updates using setInterval or mock WebSocket.\n    - Add animated counters that smoothly transition between values.\n    - Implement mini charts/sparklines showing trend data (use CSS or canvas).\n    - Add status indicators (green/yellow/red) based on thresholds.\n    - Include a \"last updated\" timestamp that refreshes automatically.",
    "Infinite Scroll": "Implement infinite scroll pagination for a content feed.\n    Requirements:\n    - Load initial batch of items (e.g., 10-20 items).\n    - Detect when user scrolls near bottom using Intersection Observer or scroll event.\n    - Fetch and append next batch of items seamlessly.\n    - Show loading spinner/skeleton during fetch.\n    - Handle end-of-content state with \"No more items\" message.\n    - Implement scroll position restoration on back navigation (optional).",
    "Async Form Validation": "Implement comprehensive async form validation with server-side checks.\n    Requirements:\n    - Real-time validation on input blur and form submit.\n    - Simulate async validation (e.g., username availability check with delay).\n    - Show loading spinner next to field during async validation.\n    - Display inline error/success messages with appropriate icons.\n    - Debounce rapid input to avoid excessive validation calls.\n    - Disable submit button while any async validation is pending.",
    "File Upload with Progress": "Implement a file upload component with progress tracking.\n    Requirements:\n    - Create a drag-and-drop zone with click-to-browse fallback.\n    - Show file preview (thumbnail for images, icon for others).\n    - Display upload progress bar with percentage for each file.\n    - Simulate upload progress using XMLHttpRequest or fetch with mock delay.\n    - Support multiple file selection and queue management.\n    - Add cancel upload and remove file functionality.",
    "Parallax Scrolling": "Implement parallax scrolling effects for visual depth.\n    Requirements:\n    - Create multiple layers that move at different speeds on scroll.\n    - Apply parallax to background images, floating elements, or text.\n    - Use transform: translate3d for GPU-accelerated smooth performance.\n    - Implement both vertical and optional horizontal parallax.\n    - Add fade-in/scale effects for elements entering viewport.\n    - Ensure graceful degradation on mobile (reduce or disable effects).",
    "Page Transitions": "Implement smooth page/view transitions for SPA-like experience.\n    Requirements:\n    - Create animated transitions between different content sections/pages.\n    - Implement multiple transition types (fade, slide, zoom, flip).\n    - Add enter/exit animations that coordinate timing.\n    - Use CSS transitions/animations or Web Animations API.\n    - Handle browser back/forward with appropriate reverse animations.\n    - Add loading state during content fetch if applicable.",
    "Particle Effects": "Implement interactive particle effects for visual enhancement.\n    Requirements:\n    - Create a canvas-based particle system with configurable particle count.\n    - Implement particle physics (velocity, gravity, friction, bounce).\n    - Add mouse/touch interaction (particles follow cursor, explode on click).\n    - Support different particle shapes (circles, squares, custom images).\n    - Implement connection lines between nearby particles (constellation effect).\n    - Optimize performance with requestAnimationFrame and particle pooling.",
    "Skeleton Loading": "Implement skeleton loading screens for improved perceived performance.\n    Requirements:\n    - Create skeleton placeholders matching the layout of actual content.\n    - Add shimmer/pulse animation effect on skeleton elements.\n    - Implement skeletons for various content types (text, images, cards, lists).\n    - Smooth transition from skeleton to actual content when loaded.\n    - Support different skeleton variants based on content type.\n    - Ensure skeletons are accessible (aria-busy, aria-label).",
    "Shopping Cart": "Implement a fully functional shopping cart system.\n    Requirements:\n    - Add \"Add to Cart\" buttons on product items with quantity selector.\n    - Create cart sidebar/dropdown showing added items with thumbnails.\n    - Implement quantity adjustment (+/-) and remove item functionality.\n    - Calculate and display subtotal, tax, and total in real-time.\n    - Persist cart data in localStorage across page refreshes.\n    - Add cart badge showing item count on cart icon.",
    "User Authentication": "Implement a complete user authentication UI flow.\n    Requirements:\n    - Create login form with email/username and password fields.\n    - Create registration form with password confirmation and terms checkbox.\n    - Implement \"Forgot Password\" flow with email input.\n    - Add form validation with appropriate error messages.\n    - Show/hide password toggle functionality.\n    - Simulate auth state with localStorage and update UI accordingly (logged in/out).",
    "Multi-step Wizard": "Implement a multi-step form wizard with progress tracking.\n    Requirements:\n    - Create a step indicator showing current step and total steps.\n    - Implement step navigation (Next, Previous, Skip if allowed).\n    - Validate each step before allowing progression.\n    - Show step completion status (completed, current, upcoming).\n    - Persist form data across steps (don't lose data on back navigation).\n    - Add final review step showing all entered data before submission.",
    "Notification Center": "Implement a notification center with real-time alerts.\n    Requirements:\n    - Create notification bell icon with unread count badge.\n    - Implement dropdown panel showing notification list.\n    - Support different notification types (info, success, warning, error).\n    - Add mark as read (individual and mark all) functionality.\n    - Implement notification grouping by date or type.\n    - Add simulated real-time notifications using setInterval or mock events.",
    "Dark Mode Toggle": "Implement a dark/light theme switcher using CSS custom properties.\n    Requirements:\n    - Define CSS variables for background, text, border, and accent colors in :root and [data-theme='dark'].\n    - Create a toggle button (sun/moon icon) in the header that switches themes.\n    - Apply smooth transition on all color changes (transition: background-color 0.3s, color 0.3s).\n    - Persist the user's preference in localStorage.\n    - Respect prefers-color-scheme media query as default on first visit.\n    - Ensure all page components respond correctly to the theme change.",
    "Accordion": "Implement collapsible accordion panels for organizing content.\n    Requirements:\n    - Create a list of header/content panel pairs that expand/collapse on header click.\n    - Only one panel open at a time (exclusive mode) or allow multiple (configurable).\n    - Animate the expand/collapse with smooth height transition (max-height or CSS grid).\n    - Show open/close indicator (chevron/plus icon) that rotates on toggle.\n    - Support keyboard navigation (Enter/Space to toggle, arrow keys between headers).\n    - Add aria-expanded and aria-controls for accessibility.",
    "Modal Dialog": "Implement a modal dialog system with backdrop overlay.\n    Requirements:\n    - Create a centered modal with semi-transparent backdrop overlay.\n    - Close on ESC key press, backdrop click, or close button.\n    - Implement focus trap (Tab cycles only within modal while open).\n    - Add open/close animation (fade + scale or slide).\n    - Prevent body scroll when modal is open (overflow: hidden on body).\n    - Support multiple modal sizes (small, medium, large) via CSS classes.",
    "Tooltip": "Implement a tooltip/popover component for contextual information.\n    Requirements:\n    - Show tooltip on hover (with 200ms delay) or focus on trigger element.\n    - Position tooltip automatically (top/bottom/left/right) based on available space.\n    - Add a small arrow/caret pointing to the trigger element.\n    - Support both plain text and rich HTML content in tooltip.\n    - Dismiss on mouse leave, blur, ESC, or scroll.\n    - Ensure tooltip stays within viewport bounds (flip if necessary).",
    "Breadcrumb Navigation": "Implement dynamic breadcrumb navigation reflecting page hierarchy.\n    Requirements:\n    - Display a horizontal breadcrumb trail showing the current navigation path.\n    - Use separator characters (/ or >) between items.\n    - Make all items except the last one clickable links.\n    - Highlight the current (last) item as non-clickable text.\n    - Add structured data (schema.org BreadcrumbList) for SEO.\n    - Truncate long paths with ellipsis on mobile (show first, last, and ellipsis).",
    "Tabs": "Implement a tabbed content interface with keyboard accessibility.\n    Requirements:\n    - Create a horizontal tab bar with multiple tab buttons.\n    - Show/hide corresponding tab panels when a tab is clicked.\n    - Style the active tab distinctly (border-bottom, background change, or underline).\n    - Support keyboard navigation (arrow keys between tabs, Enter/Space to select).\n    - Implement proper ARIA roles (tablist, tab, tabpanel) with aria-selected.\n    - Add smooth fade or slide transition when switching panels.",
    "Toast Notifications": "Implement an auto-dismissing toast notification system.\n    Requirements:\n    - Display toast messages at a fixed screen position (top-right or bottom-right).\n    - Support multiple types: success (green), error (red), warning (yellow), info (blue).\n    - Auto-dismiss after configurable duration (default 5 seconds) with progress bar.\n    - Stack multiple toasts vertically with smooth entrance/exit animations.\n    - Allow manual dismiss via close button.\n    - Pause auto-dismiss timer on hover.",
    "Star Rating": "Implement an interactive star rating widget.\n    Requirements:\n    - Display 5 clickable star icons in a row.\n    - Highlight stars on hover to preview the rating (fill stars up to cursor).\n    - On click, set the rating and keep stars filled.\n    - Support half-star precision (optional).\n    - Show numeric rating value next to the stars.\n    - Add visual feedback animation on selection (brief scale pulse).\n    - Make it accessible with aria-label and keyboard support (arrow keys).",
    "Copy to Clipboard": "Implement copy-to-clipboard functionality with visual feedback.\n    Requirements:\n    - Add a copy button next to code blocks or text content.\n    - Use navigator.clipboard.writeText() API with fallback for older browsers.\n    - Show visual confirmation on copy (icon changes to checkmark, tooltip says 'Copied!').\n    - Revert the icon/text back to original state after 2 seconds.\n    - Support copying from multiple elements on the same page.\n    - Style the button to blend with the content context (inline or floating).",
    "Back to Top": "Implement a smooth scroll-to-top button.\n    Requirements:\n    - Show a floating button (fixed position, bottom-right) when user scrolls down >300px.\n    - Hide the button with fade animation when near the top.\n    - On click, smoothly scroll to page top using window.scrollTo with behavior: 'smooth'.\n    - Add a subtle hover effect (scale or shadow increase).\n    - Use an upward arrow icon inside a circular button.\n    - Ensure the button doesn't overlap important content (add appropriate z-index).",
    "Cookie Consent": "Implement a GDPR-compliant cookie consent banner.\n    Requirements:\n    - Display a fixed banner at the bottom of the page on first visit.\n    - Include 'Accept All', 'Reject All', and 'Customize' buttons.\n    - 'Customize' opens a panel with toggle switches for cookie categories (Essential, Analytics, Marketing).\n    - Store the user's choice in localStorage; don't show banner again once decided.\n    - Add a small 'Cookie Settings' link in the footer to re-open preferences.\n    - Animate the banner entrance (slide up) and exit (slide down).",
    "Responsive Navigation": "Implement a responsive navigation with mobile hamburger menu.\n    Requirements:\n    - On desktop (>768px): show a horizontal nav bar with all menu items visible.\n    - On mobile (<=768px): collapse nav into a hamburger icon (three lines).\n    - Clicking hamburger opens a full-height sidebar or dropdown with menu items.\n    - Animate the menu open/close (slide-in from left or fade-down).\n    - Close the menu on link click, outside click, or ESC key.\n    - Add smooth transition for the hamburger icon to X (close) transformation.",
    "Sticky Header": "Implement a sticky header with scroll spy highlighting.\n    Requirements:\n    - Make the header fixed at the top when scrolling past its natural position.\n    - Add a subtle shadow or border-bottom when the header becomes sticky.\n    - Implement scroll spy: highlight the nav link corresponding to the currently visible section.\n    - Use Intersection Observer to detect which section is in view.\n    - Smooth scroll to section when clicking nav links (scroll-behavior or JS).\n    - Optionally shrink/transform the header on scroll (smaller height, logo resize).",
    "Search Autocomplete": "Implement a search input with dropdown autocomplete suggestions.\n    Requirements:\n    - Create a search input field with a search icon.\n    - Show a dropdown of matching suggestions as the user types.\n    - Debounce input to avoid excessive filtering (300ms delay).\n    - Highlight the matching text portion in each suggestion.\n    - Support keyboard navigation in the dropdown (arrow up/down, Enter to select, ESC to close).\n    - Show 'No results found' when no matches; show recent searches when input is empty.",
    "Image Lightbox": "Implement a full-screen image lightbox gallery.\n    Requirements:\n    - Display a grid/list of thumbnail images that open in lightbox on click.\n    - Lightbox shows the full-size image centered on a dark backdrop.\n    - Add previous/next navigation arrows to browse through images.\n    - Support keyboard navigation (arrow keys, ESC to close).\n    - Add smooth zoom/fade animation on open and close.\n    - Show image caption and counter (e.g., '3 of 12') below the image.",
    "Countdown Timer": "Implement an animated countdown timer display.\n    Requirements:\n    - Display days, hours, minutes, and seconds in separate styled boxes.\n    - Update every second using setInterval with smooth digit transitions.\n    - Add flip or fade animation when digits change.\n    - Accept a target date/time as configuration.\n    - Show 'Time expired!' or trigger an action when countdown reaches zero.\n    - Style with clear visual hierarchy (large numbers, small labels below).",
    "Color Picker": "Implement an interactive color picker component.\n    Requirements:\n    - Create a color spectrum canvas (hue/saturation gradient) for visual selection.\n    - Add a hue slider bar for selecting the base hue.\n    - Display the selected color as a preview swatch.\n    - Show hex, RGB, and HSL values that update in real-time.\n    - Allow manual input of hex/RGB values with validation.\n    - Add preset color swatches for quick selection.\n    - Copy hex value to clipboard on click of the preview swatch.",
    "Date Picker": "Implement a calendar-based date picker component.\n    Requirements:\n    - Create a text input that opens a calendar dropdown on click/focus.\n    - Display a month grid with selectable day cells.\n    - Add month/year navigation (previous/next arrows, month/year dropdowns).\n    - Highlight today's date and the selected date distinctly.\n    - Disable dates outside a valid range if configured.\n    - Close the calendar on date selection or outside click.\n    - Format and display the selected date in the input field.",
    "Carousel": "Implement a content carousel/slider with navigation controls.\n    Requirements:\n    - Display one slide at a time (or multiple in a row) with smooth horizontal sliding.\n    - Add previous/next arrow buttons on the sides.\n    - Add dot indicators below showing the current slide position.\n    - Support auto-play with configurable interval and pause-on-hover.\n    - Implement infinite loop (wrap from last to first slide seamlessly).\n    - Add swipe/drag support for touch devices.\n    - Ensure smooth CSS transition between slides.",
    "Keyboard Shortcuts": "Implement a keyboard shortcuts system with help overlay.\n    Requirements:\n    - Register global keyboard shortcuts (e.g., Ctrl+K for search, ? for help).\n    - Create a help overlay (modal) showing all available shortcuts in a grid.\n    - Toggle the help panel with '?' key press.\n    - Prevent shortcuts from firing when user is typing in input/textarea fields.\n    - Group shortcuts by category (Navigation, Actions, Editing).\n    - Show visual key badges (styled kbd elements) next to each shortcut description.",
    "Context Menu": "Implement a custom right-click context menu.\n    Requirements:\n    - Override the default browser context menu on specific elements or the page.\n    - Show a styled dropdown menu at the cursor position on right-click.\n    - Include menu items with icons, text, and optional keyboard shortcut hints.\n    - Support nested submenus (hover to expand).\n    - Close the menu on item click, outside click, or ESC.\n    - Position the menu to stay within viewport bounds (flip if near edge).",
    "Lazy Loading Images": "Implement lazy loading for images with placeholder effects.\n    Requirements:\n    - Defer loading of off-screen images until they enter the viewport.\n    - Use Intersection Observer API to detect visibility.\n    - Show a blurred low-resolution placeholder or solid color box while loading.\n    - Animate the transition from placeholder to full image (fade-in).\n    - Add loading='lazy' attribute as progressive enhancement.\n    - Handle error state with a fallback broken-image indicator.",
    "Print Stylesheet": "Implement an optimized print layout using CSS @media print.\n    Requirements:\n    - Hide navigation, footer, ads, and interactive elements when printing.\n    - Expand all collapsed/accordion content so nothing is hidden.\n    - Force a white background with black text for readability and ink saving.\n    - Display URLs after links in parentheses (content: ' (' attr(href) ')').\n    - Add page-break-inside: avoid on cards, images, and tables.\n    - Add a 'Print this page' button that triggers window.print().",
    "Undo Redo": "Implement an undo/redo system for user actions.\n    Requirements:\n    - Track user modifications in a history stack (array of state snapshots or commands).\n    - Add Undo (Ctrl+Z) and Redo (Ctrl+Shift+Z or Ctrl+Y) keyboard shortcuts.\n    - Create visible Undo/Redo buttons in the UI with disabled state when unavailable.\n    - Support at least 20 levels of undo history.\n    - Clear the redo stack when a new action is performed after undoing.\n    - Show a brief indicator or toast when undo/redo is performed.",
}

_DEFECT_TYPES: list[str] = [
    "Occlusion",
    "Crowding",
    "Text Overlap",
    "Alignment",
    "Color Contrast",
    "Overflow",
    "Sizing Proportion",
    "Loss of Interactivity",
    "Semantic Error",
    "Nesting Error",
    "Missing Attributes",
]

_DEFECT_DESCRIPTIONS: dict[str, str] = {
    "Occlusion": "Increase the z-index of element A so that it covers element B.\n    For example, make a modal overlay cover important content, or make a fixed header cover interactive elements.",
    "Crowding": "Remove margin or padding between elements A and B, or shrink their parent container size.\n    For example, remove spacing between navigation items, or collapse the gap between form fields.",
    "Text Overlap": "Reduce the width or line-height of a text container, or position two text containers at the same location.\n    For example, make text overflow its container and overlap with adjacent elements.",
    "Alignment": "Adjust the left/top properties of element A so it's not aligned with the grid or sibling element B.\n    For example, misalign navigation items, or offset a button from its expected position.",
    "Color Contrast": "Set text color to a value similar to the background color (e.g., light gray text on white background).\n    For example, make body text nearly invisible, or reduce contrast of important labels.",
    "Overflow": "Add excessive content to a fixed height/width container and set overflow: visible or remove overflow handling.\n    For example, add too much text to a card component causing it to break layout.",
    "Sizing Proportion": "Set an image to extreme dimensions (e.g., width: 10px, height: 200px), or make a container unnecessarily huge.\n    For example, distort an image aspect ratio, or make a small icon take up entire width.",
    "Loss of Interactivity": "Disable a button element, or use CSS pointer-events: none to make a link unclickable.\n    For example, add disabled attribute to submit button, or block clicks on navigation links.",
    "Semantic Error": "Replace heading <h1> element with <div> element styled the same way.\n    For example, convert semantic nav to div, or replace button with styled span.",
    "Nesting Error": "Place an <a> tag inside another <a> tag, or put a <div> inside a <p> tag.\n    For example, nest block elements inside inline elements incorrectly.",
    "Missing Attributes": "Remove alt attribute from <img> elements, or remove aria-label from form inputs.\n    For example, remove accessibility attributes, or remove required form attributes.",
}


def load_edit_catalog() -> tuple[list[str], dict[str, str]]:
    return list(_EDIT_TASKS), dict(_EDIT_TASK_DESCRIPTIONS)


def load_repair_catalog() -> tuple[list[str], dict[str, str]]:
    return list(_DEFECT_TYPES), dict(_DEFECT_DESCRIPTIONS)


def _normalize_whitespace(text: str) -> str:
    """Collapse all whitespace runs to single spaces for fuzzy matching."""
    return re.sub(r"\s+", " ", text.strip())


def _fuzzy_replace(code: str, search_text: str, replace_text: str) -> str | None:
    """Try whitespace-normalized matching as fallback.

    Finds the substring in code whose normalized form matches normalized search_text,
    then replaces that exact substring with replace_text.
    """
    norm_search = _normalize_whitespace(search_text)
    if not norm_search:
        return None
    # Sliding window: normalize chunks of code and look for match
    # Use a line-based approach for efficiency
    code_lines = code.split("\n")
    search_lines = search_text.strip().split("\n")
    n_search = len(search_lines)
    for start in range(len(code_lines) - n_search + 1):
        candidate = "\n".join(code_lines[start : start + n_search])
        if _normalize_whitespace(candidate) == norm_search:
            return code.replace(candidate, replace_text, 1)
    # Also try with varying window sizes (+/- 2 lines)
    for delta in range(1, 3):
        for start in range(len(code_lines)):
            for size in (n_search + delta, n_search - delta):
                if size <= 0 or start + size > len(code_lines):
                    continue
                candidate = "\n".join(code_lines[start : start + size])
                if _normalize_whitespace(candidate) == norm_search:
                    return code.replace(candidate, replace_text, 1)
    return None


def apply_search_replace_local(
    code_list: list[dict[str, str]], modified_files: list[dict[str, str]], strict_mode: bool = True
) -> tuple[list[dict[str, str]], list[dict[str, Any]]]:
    """Local copy of web_coding_demo.utils.apply_search_replace without heavyweight image deps."""
    result_code = []
    code_map = {item["path"]: item["code"] for item in code_list}
    errors: list[dict[str, Any]] = []
    blocks_by_path: dict[str, list[dict[str, str]]] = {}
    for block in modified_files:
        blocks_by_path.setdefault(block["path"], []).append(block)

    for path, blocks in blocks_by_path.items():
        if path not in code_map:
            if blocks and blocks[0]["search"] == "":
                code_map[path] = ""
            else:
                error_msg = f"File path not found in code_list: {path}"
                if strict_mode:
                    raise ValueError(error_msg)
                errors.extend(
                    {"path": path, "block_index": idx, "error_type": "path_not_found", "error": error_msg}
                    for idx, _ in enumerate(blocks)
                )
                continue

        code = code_map[path]
        for block_idx, block in enumerate(blocks):
            search_text = block["search"]
            replace_text = block["replace"]
            if search_text.strip() == replace_text.strip():
                error_msg = f"Search and replace are identical in {path} (block {block_idx})."
                if strict_mode:
                    raise ValueError(error_msg)
                errors.append(
                    {
                        "path": path,
                        "block_index": block_idx,
                        "error_type": "identical_search_replace",
                        "error": error_msg,
                    }
                )
                continue
            if search_text == "" and code == "":
                code = replace_text
            elif search_text in code:
                code = code.replace(search_text, replace_text, 1)
            elif _fuzzy_replace(code, search_text, replace_text) is not None:
                code = _fuzzy_replace(code, search_text, replace_text)
            else:
                error_msg = (
                    f"Failed to apply search/replace in {path} (block {block_idx}).\n"
                    f"Search text (first 200 chars): {search_text[:200]}...\n"
                    "This may indicate LLM generated invalid modifications."
                )
                if strict_mode:
                    raise ValueError(error_msg)
                errors.append(
                    {"path": path, "block_index": block_idx, "error_type": "search_not_found", "error": error_msg}
                )
                continue
        code_map[path] = code

    existing_paths = {item["path"] for item in code_list}
    for item in code_list:
        new_item = item.copy()
        if item["path"] in code_map:
            new_item["code"] = code_map[item["path"]]
        result_code.append(new_item)
    for path, content in code_map.items():
        if path not in existing_paths:
            result_code.append({"path": path, "code": content})
    return result_code, errors


class LocalSearchReplaceSynthesizer:
    """Dependency-light adapter for web_coding_demo.synthetic.synthesizer.BaseSynthesizer."""

    def __init__(
        self,
        api_key: str,
        base_url: str | None = None,
        model: str = "gpt-4o",
        max_tokens: int = 8192,
        max_retries: int = 3,
    ):
        from openai import OpenAI

        self.client = OpenAI(api_key=api_key, base_url=base_url, timeout=300.0)
        self.model = model
        self.max_tokens = max_tokens
        self.max_retries = max_retries

    def format_code_context(self, code_list: list[dict[str, str]], max_tokens: int = 200_000) -> str:
        """Build XML context for LLM — only HTML files.

        CSS/JS are kept in src_code/info.json but not sent to LLM.
        Token estimation: ~1 token per 4 chars for ASCII code.
        """
        max_chars = max_tokens * 4
        html_exts = {".html", ".htm"}
        html_items = [it for it in code_list if Path(it["path"]).suffix.lower() in html_exts]

        context = "<code_context>\n"
        remaining = max_chars
        for item in sorted(html_items, key=lambda it: it["path"]):
            if remaining <= 0:
                break
            code = _truncate_text(item["code"], remaining)
            context += f'<file path="{item["path"]}">\n{code}\n</file>\n'
            remaining -= len(code)
        context += "</code_context>"
        return context

    def parse_llm_response(self, response_text: str) -> dict[str, Any]:
        response_text = strip_markdown_fence(response_text)
        desc_match = re.search(r"<description>(.*?)</description>", response_text, re.DOTALL)
        if not desc_match:
            raise ValueError("No <description> tag found in LLM response")
        description = json.loads(desc_match.group(1).strip())

        sr_matches = re.findall(
            r'<search_replace\s+path="([^"]+)">\s*<search>(.*?)</search>\s*<replace>(.*?)</replace>\s*</search_replace>',
            response_text,
            re.DOTALL,
        )
        modified_files = []
        for path, search, replace in sr_matches:
            search_stripped = search.strip()
            replace_stripped = replace.strip()
            if search_stripped == replace_stripped:
                continue
            modified_files.append(
                {"path": path.strip(), "search": search_stripped, "replace": replace_stripped}
            )
        return {"description": description, "modified_files": modified_files}

    def _validate_task_types(self, description: list[dict[str, Any]], expected_task_types: list[str] | None = None) -> None:
        if not expected_task_types:
            return
        actual_task_types = []
        for idx, item in enumerate(description):
            task_type = item.get("task_type")
            if not task_type:
                raise ValueError(f"Missing task_type at index {idx}: {item}")
            actual_task_types.append(task_type)
        if len(actual_task_types) != len(expected_task_types):
            raise ValueError(
                f"Task type count mismatch: got {len(actual_task_types)}, expected {len(expected_task_types)}"
            )
        if Counter(actual_task_types) != Counter(expected_task_types):
            raise ValueError(f"Task types do not match expected list. got={actual_task_types}, expected={expected_task_types}")

    def _generate(
        self,
        messages: list[dict[str, Any]],
        max_retries: int = 3,
        backoff_base: int = 2,
    ) -> dict[str, Any]:
        """Call LLM and parse response. No patch application."""
        last_error: Exception | None = None
        for attempt in range(1, max_retries + 1):
            try:
                response = self.client.chat.completions.create(
                    model=self.model,
                    messages=messages,
                    max_tokens=self.max_tokens,
                )
                response_text = response.choices[0].message.content if response and response.choices else None
                if not response_text:
                    raise ValueError("Empty response content from LLM.")
                print(f"LLM response received (attempt {attempt})")

                parsed = self.parse_llm_response(response_text)
                if not parsed.get("modified_files"):
                    raise ValueError("Parsed LLM response has no modified_files.")

                return {
                    "description": parsed.get("description", []),
                    "modified_files": parsed["modified_files"],
                    "raw_response": response_text,
                    "llm_metadata": {"model": self.model, "attempt": attempt},
                }
            except Exception as exc:
                last_error = exc
                print(f"Attempt {attempt}/{max_retries} failed: {exc}")
                if attempt < max_retries:
                    time.sleep(backoff_base**attempt)
        raise Exception(f"Failed after {max_retries} attempts. Last error: {last_error}") from last_error


def build_forward_edit_synthesizer(api_key: str, base_url: str | None, model: str, max_retries: int = 3):
    _, task_descriptions = load_edit_catalog()

    class ForwardEditPairSynthesizer(LocalSearchReplaceSynthesizer):
        def generate_forward_pair(self, generation_data: dict[str, Any], task_types: list[str]) -> dict[str, Any]:
            src_code = generation_data["dst_code"]
            src_code_context = self.format_code_context(src_code)
            task_descriptions_str = ""
            for idx, task_type in enumerate(task_types, 1):
                task_descriptions_str += f"Task {idx}: {task_type}\n  Guideline: {task_descriptions[task_type]}\n\n"
            task_types_json = json.dumps(task_types, ensure_ascii=False)
            prompt = f"""Generate {len(task_types)} editing tasks for the webpage below. Output ONLY XML, no explanation.

Tasks:
{task_descriptions_str}
task_type values: {task_types_json}

Output format (nothing else):
<description>[{{"task_type": "...", "description": "..."}}]</description>
<search_replace path="path/to/file"><search>exact source text</search><replace>edited text</replace></search_replace>

{src_code_context}"""

            result = self._generate(
                messages=[
                    {
                        "role": "system",
                        "content": "Output ONLY XML. No explanations, no markdown fences, no commentary.",
                    },
                    {"role": "user", "content": prompt},
                ],
                max_retries=self.max_retries,
            )
            return {
                "task": "edit",
                "task_type": task_types,
                "description": result["description"],
                "resources": generation_data.get("resources", []),
                "label_modified_files": result.get("modified_files", []),
                "llm_raw_response": result.get("raw_response"),
                "llm_metadata": result.get("llm_metadata"),
            }

        def process_single_generation_entry(self, *args, **kwargs) -> list[dict[str, Any]]:
            raise NotImplementedError

    return ForwardEditPairSynthesizer(api_key, base_url, model, max_tokens=16_384, max_retries=max_retries)


def build_repair_synthesizer(api_key: str, base_url: str | None, model: str, max_retries: int = 3):
    _, defect_descriptions = load_repair_catalog()

    class RepairPairSynthesizer(LocalSearchReplaceSynthesizer):
        def generate_defect_task(self, generation_data: dict[str, Any], defect_types: list[str]) -> dict[str, Any]:
            dst_code = generation_data["dst_code"]
            dst_code_context = self.format_code_context(dst_code)
            defect_descriptions_str = ""
            for idx, defect_type in enumerate(defect_types, 1):
                defect_descriptions_str += f"Defect {idx}: {defect_type}\n  Guideline: {defect_descriptions[defect_type]}\n\n"
            defect_types_json = json.dumps(defect_types, ensure_ascii=False)
            prompt = f"""Inject {len(defect_types)} defects into the webpage below. Output ONLY XML, no explanation.

Defects:
{defect_descriptions_str}
task_type values: {defect_types_json}

Output format (nothing else):
<description>[{{"task_type": "...", "description": "repair instruction"}}]</description>
<search_replace path="path/to/file"><search>exact clean text</search><replace>defective text</replace></search_replace>

{dst_code_context}"""
            result = self._generate(
                messages=[
                    {
                        "role": "system",
                        "content": "Output ONLY XML. No explanations, no markdown fences, no commentary.",
                    },
                    {"role": "user", "content": prompt},
                ],
                max_retries=self.max_retries,
            )
            # For repair: LLM's search = clean code, replace = defective code
            # label is the *fix* direction: search = defective, replace = clean
            label_modified_files = [
                {"path": mod["path"], "search": mod["replace"], "replace": mod["search"]}
                for mod in result.get("modified_files", [])
            ]
            return {
                "task": "repair",
                "task_type": defect_types,
                "description": result["description"],
                "resources": generation_data.get("resources", []),
                "label_modified_files": label_modified_files,
                "llm_raw_response": result.get("raw_response"),
                "llm_metadata": result.get("llm_metadata"),
            }

    return RepairPairSynthesizer(api_key, base_url, model, max_tokens=16_384, max_retries=max_retries)
