from __future__ import annotations

import json
import os
import random
import re
import shutil
import sys
import ast
import time
from collections import Counter
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
WEB_CODING_DEMO_ROOT = REPO_ROOT / "web_coding_demo"
if str(WEB_CODING_DEMO_ROOT) not in sys.path:
    sys.path.insert(0, str(WEB_CODING_DEMO_ROOT))

CODE_EXTS = {".html", ".htm", ".css", ".js", ".jsx", ".ts", ".tsx", ".json", ".svg"}
PROVENANCE_FILES = {"metadata.json", "original_webcode2m_screenshot.png"}
REMOTE_URL_RE = re.compile(r"https?://[^\s\"'<>)]*", re.I)
SVG_NAMESPACE_URLS = {
    "http://www.w3.org/2000/svg",
    "http://www.w3.org/1999/xlink",
    "http://purl.org/dc/elements/1.1/",
    "http://creativecommons.org/ns#",
    "http://www.inkscape.org/namespaces/inkscape",
    "http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd",
    "http://www.serif.com/",
}
VIEWPORTS = [
    ("desktop", 1920, 1080),
    ("tablet", 768, 1024),
    ("mobile", 375, 812),
]
TEXT_PRD_PROMPT = """You are writing a complete implementation brief for a developer who must recreate an entire website project from scratch.
You will be shown full-page captures from every HTML page in the project, usually across desktop, tablet, and mobile layouts.

Write a detailed PRD-style instruction that is specific enough for implementation. It must describe the actual website in the inputs, not a generic website template.

What the final instruction must do:
- Cover the full project, not just the homepage.
- Explain the shared site shell first, then page-specific requirements.
- Describe information architecture, navigation, page hierarchy, hero areas, cards, lists, forms, media, CTAs, footer content, and repeated modules.
- Include interaction behavior that is visually implied, such as menus, tabs, sliders, modals, validation states, hover states, expandable sections, or user flows.
- Capture responsive differences when layout or hierarchy changes between desktop, tablet, and mobile.
- Preserve the website's visible tone, industry, audience, visual density, and content character.
- Be concrete about what appears on the page, but do not drift into CSS pixel trivia or code-level selectors.

Hard constraints:
- Do not mention screenshots, images, captures, source website, reverse engineering, benchmark datasets, or hidden implementation context.
- Do not say vague things like "build a modern website" without grounding them in the actual pages.
- Do not invent backend behavior that is not supported by visible evidence.
- If content is repeated across pages, describe the reusable pattern once and then note page-specific differences.
- If the pages contain placeholder, autogenerated, or provenance-revealing copy such as "generated page", "training project", "demo page", or similar boilerplate, do not repeat that provenance language in the final brief. Instead, describe the visible page structure and intended role in neutral product language.

Output exactly these sections:
# Project overview
# Global structure and navigation
# Page-by-page requirements
# Interaction and state requirements
# Responsive behavior
# Visual language and content details
"""
CHUNK_PROMPT = TEXT_PRD_PROMPT + """

For this batch only, do not write the final full brief yet.
Instead, extract high-signal implementation notes from the current pages only.

Requirements for the batch notes:
- Be concise but information-dense.
- Name the pages in this batch.
- List the main sections in visual order.
- Note any repeated modules, navigation patterns, form fields, content blocks, and visual motifs.
- Record only interactions that are clearly implied by the visible UI.
- Highlight responsive differences that are visible within this batch.
- Ignore obvious provenance or placeholder boilerplate if it only explains that the page is autogenerated, for training, or for demonstration. Replace that with a neutral description of the page's functional role.

Keep the same section headers as the final brief.
"""
MERGE_PROMPT = """Combine the following batch notes into one complete implementation brief for a developer.

The final brief must:
- read like a single coherent product/design specification
- cover every distinct page and shared module
- preserve concrete content, layout, and interaction details
- stay implementation-oriented without exposing source-analysis context

Do not mention batches, screenshots, images, reverse engineering, dataset names, or internal generation process.

Use exactly these sections:
# Project overview
# Global structure and navigation
# Page-by-page requirements
# Interaction and state requirements
# Responsive behavior
# Visual language and content details

Batch notes:
---
{notes}
---
"""


def maybe_load_env() -> None:
    try:
        from dotenv import load_dotenv
    except Exception:
        return
    for candidate in (REPO_ROOT / "WebCoding_Data" / ".env", REPO_ROOT / ".env"):
        if candidate.exists():
            load_dotenv(candidate)


def safe_write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def append_jsonl(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(payload, ensure_ascii=False) + "\n")


def iter_project_dirs(root: Path, limit: int = 0) -> list[Path]:
    projects = sorted(p for p in root.iterdir() if p.is_dir())
    return projects[:limit] if limit > 0 else projects


def find_html_pages(project_dir: Path) -> list[Path]:
    pages = []
    for page in sorted(project_dir.rglob("*.html")):
        rel_parts = page.relative_to(project_dir).parts
        if any(part.lower() in {"resources", "assets", "static", "node_modules"} for part in rel_parts[:-1]):
            continue
        pages.append(page)
    index = project_dir / "index.html"
    if index.exists() and index not in pages:
        pages.insert(0, index)
    return pages


def infer_page_bucket(project_dir: Path) -> str:
    return "mp" if len(find_html_pages(project_dir)) >= 2 else "sp"


def read_code_bundle(project_dir: Path) -> list[dict[str, str]]:
    code = []
    for path in sorted(project_dir.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix.lower() not in CODE_EXTS:
            continue
        rel = path.relative_to(project_dir).as_posix()
        if rel in PROVENANCE_FILES:
            continue
        code.append({"path": rel, "code": sanitize_render_text(path.read_text("utf-8", errors="ignore"))})
    return code


def collect_resources(project_dir: Path) -> list[dict[str, Any]]:
    resources = []
    for path in sorted(project_dir.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(project_dir).as_posix()
        if rel in PROVENANCE_FILES:
            continue
        if path.suffix.lower() in CODE_EXTS:
            continue
        kind = "image"
        if path.suffix.lower() in {".woff", ".woff2", ".ttf", ".otf", ".eot"}:
            kind = "font"
        elif path.suffix.lower() in {".mp4", ".webm"}:
            kind = "video"
        resources.append({"path": rel, "type": kind, "size_bytes": path.stat().st_size})
    return resources


def copy_project(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns(*PROVENANCE_FILES))
    sanitize_project_files(dst)


def sanitize_render_text(text: str) -> str:
    def replace_url(match: re.Match[str]) -> str:
        url = match.group(0)
        if url in SVG_NAMESPACE_URLS:
            return url
        return "#"

    text = re.sub(r"url\(\s*(['\"]?)https?://[^'\"\)]*\1\s*\)", "url(\"\")", text, flags=re.I)
    text = re.sub(r"@import\s+(['\"])https?://[^'\"]*\1\s*;?", "", text, flags=re.I)
    return REMOTE_URL_RE.sub(replace_url, text)


def sanitize_project_files(project_dir: Path) -> None:
    for path in project_dir.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in (CODE_EXTS - {".json"}):
            continue
        text = path.read_text("utf-8", errors="ignore")
        sanitized = sanitize_render_text(text)
        if sanitized != text:
            path.write_text(sanitized, encoding="utf-8")


def write_code_bundle(code_bundle: list[dict[str, str]], out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for item in code_bundle:
        target = out_dir / item["path"]
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(item["code"], encoding="utf-8")


def write_code_bundle_from_source(source_project: Path, code_bundle: list[dict[str, str]], out_dir: Path) -> None:
    copy_project(source_project, out_dir)
    for item in code_bundle:
        target = out_dir / item["path"]
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(item["code"], encoding="utf-8")


def serialize_patch_xml(modified_files: list[dict[str, str]]) -> str:
    blocks = []
    for patch in modified_files:
        blocks.append(
            "<search>\n"
            f"{patch['search']}\n"
            "</search>\n"
            "<replace>\n"
            f"{patch['replace']}\n"
            "</replace>"
        )
    return "\n".join(blocks)


def choose_task_types(all_task_types: list[str], count: int, seed: int | None, instance_id: str) -> list[str]:
    rng = random.Random(f"{seed}:{instance_id}" if seed is not None else instance_id)
    if count > len(all_task_types):
        raise ValueError(f"Requested {count} task types, only {len(all_task_types)} available")
    return rng.sample(all_task_types, count)


def safe_name(value: str) -> str:
    value = str(value).replace(os.sep, "__")
    return re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("_") or "page"


def route_local_only(route) -> None:
    url = route.request.url
    if url.startswith(("file://", "data:", "blob:")):
        route.continue_()
    else:
        route.abort("connectionfailed")


def screenshot_project_to_dir(project_dir: Path, out_dir: Path) -> list[dict[str, str]]:
    from playwright.sync_api import sync_playwright

    pages = find_html_pages(project_dir)
    if not pages:
        raise RuntimeError("no html pages found")
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, str]] = []
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        for html in pages:
            rel = html.relative_to(project_dir).as_posix()
            page_key = safe_name(rel[:-5] if rel.lower().endswith(".html") else rel)
            for vp_name, width, height in VIEWPORTS:
                page = browser.new_page(viewport={"width": width, "height": height})
                page.route("**/*", route_local_only)
                try:
                    page.goto("file://" + str(html.resolve()), wait_until="domcontentloaded", timeout=20000)
                    page.wait_for_timeout(1000)
                    dest = out_dir / f"{page_key}__{vp_name}.jpg"
                    page.screenshot(path=str(dest), full_page=True, type="jpeg", quality=82, timeout=90000)
                    records.append({"page": rel, "viewport": vp_name, "path": dest.relative_to(out_dir.parent).as_posix()})
                finally:
                    page.close()
        browser.close()
    return records


def record_project_to_dir(project_dir: Path, out_dir: Path) -> list[dict[str, Any]]:
    from playwright.sync_api import sync_playwright

    pages = find_html_pages(project_dir)
    if not pages:
        raise RuntimeError("no html pages found")
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, Any]] = []
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        for html in pages:
            rel = html.relative_to(project_dir).as_posix()
            page_key = safe_name(rel[:-5] if rel.lower().endswith(".html") else rel)
            record_dir = out_dir / f"{page_key}_recording"
            record_dir.mkdir(parents=True, exist_ok=True)
            context = browser.new_context(
                viewport={"width": 1280, "height": 720},
                record_video_dir=str(record_dir),
                record_video_size={"width": 1280, "height": 720},
            )
            page = context.new_page()
            page.route("**/*", route_local_only)
            try:
                page.goto("file://" + str(html.resolve()), wait_until="domcontentloaded", timeout=30000)
                page.wait_for_timeout(1500)

                # Use human-like interaction instead of mechanical scrolling
                from WebCoding_Data.construct.human_like_playwright_record import HumanRecorder, run_story

                recorder = HumanRecorder(page, record_dir, time.time())
                run_story(page, recorder)
                recorder.pause(800, 1200, "final_pause")
            finally:
                video = page.video
                context.close()
                if video:
                    raw_video = Path(video.path())
                    if raw_video.exists():
                        final = out_dir / f"{page_key}.webm"
                        if final.exists():
                            final.unlink()
                        shutil.move(str(raw_video), final)
                        records.append({"page": rel, "path": final.relative_to(out_dir.parent).as_posix()})
                shutil.rmtree(record_dir, ignore_errors=True)
        browser.close()
    return records


def encode_image_for_api(path: Path, max_width: int = 1200, max_bytes: int = 3_500_000) -> str:
    import base64
    from PIL import Image

    img = Image.open(path).convert("RGB")
    if img.width > max_width:
        ratio = max_width / img.width
        img = img.resize((max_width, max(1, int(img.height * ratio))))

    tmp = Path(str(path) + ".api.jpg")
    quality = 82
    while True:
        img.save(tmp, "JPEG", quality=quality, optimize=True)
        if tmp.stat().st_size <= max_bytes or quality <= 50:
            data = tmp.read_bytes()
            tmp.unlink(missing_ok=True)
            return base64.b64encode(data).decode("utf-8")
        quality -= 8


def call_vlm(model: str, prompt: str, image_paths: list[Path] | None = None, max_tokens: int = 4096) -> str:
    from openai import OpenAI

    maybe_load_env()
    api_key, base_url, _ = ensure_api_env(prefer_vision=True)
    client = OpenAI(api_key=api_key, base_url=base_url, timeout=180.0)
    if image_paths:
        content: list[dict[str, Any]] = [{"type": "text", "text": prompt}]
        use_qwen37_image = model.lower() == "qwen3.7-max"
        for image_path in image_paths:
            b64 = encode_image_for_api(image_path)
            data_url = f"data:image/jpeg;base64,{b64}"
            if use_qwen37_image:
                content.append({"type": "image", "image": data_url})
            else:
                content.append({"type": "image_url", "image_url": {"url": data_url}})
        messages = [{"role": "user", "content": content}]
    else:
        messages = [{"role": "user", "content": prompt}]
    response = client.chat.completions.create(model=model, messages=messages, max_tokens=max_tokens)
    return response.choices[0].message.content or ""


def _truncate_text(value: str, limit: int) -> str:
    if len(value) <= limit:
        return value
    return value[:limit] + "\n<!-- truncated for PRD synthesis -->"


def code_context_for_prd(project_dir: Path, page_names: set[str] | None = None, max_chars: int = 18000) -> str:
    """Build a compact source context so PRDs are grounded in code and screenshots."""
    code_items = read_code_bundle(project_dir)
    selected: list[dict[str, str]] = []
    page_names = page_names or set()
    for item in code_items:
        path = item["path"]
        suffix = Path(path).suffix.lower()
        if path in page_names or suffix in {".css", ".js", ".jsx", ".ts", ".tsx"}:
            selected.append(item)
    if not selected:
        selected = code_items[:8]

    chunks: list[str] = []
    remaining = max_chars
    for item in selected:
        if remaining <= 0:
            break
        code = _truncate_text(item["code"], min(remaining, 5000))
        chunks.append(f'<file path="{item["path"]}">\n{code}\n</file>')
        remaining -= len(code)
    return "<source_context>\n" + "\n".join(chunks) + "\n</source_context>"


def generate_prd(project_dir: Path, screenshots_dir: Path) -> tuple[str, list[dict[str, str]]]:
    maybe_load_env()
    _, _, model = ensure_api_env(prefer_vision=True)
    screenshots = screenshot_project_to_dir(project_dir, screenshots_dir)
    paths = [screenshots_dir.parent / shot["path"] for shot in screenshots]
    notes: list[str] = []
    chunk_size = 4
    for start in range(0, len(paths), chunk_size):
        chunk = paths[start : start + chunk_size]
        labels = "\n".join(
            f"- {screenshots[idx]['page']} ({screenshots[idx]['viewport']})"
            for idx in range(start, min(start + chunk_size, len(paths)))
        )
        page_names = {screenshots[idx]["page"] for idx in range(start, min(start + chunk_size, len(paths)))}
        source_context = code_context_for_prd(project_dir, page_names)
        prompt = (
            CHUNK_PROMPT
            + "\n\nPages in this batch:\n"
            + labels
            + "\n\nUse these source files together with the screenshots. The final notes must be grounded in both visual evidence and implementation structure:\n"
            + source_context
        )
        notes.append(call_vlm(model, prompt, chunk, max_tokens=1600))
    merge_source_context = code_context_for_prd(project_dir, None, max_chars=22000)
    instruction = (
        notes[0]
        if len(notes) == 1
        else call_vlm(
            model,
            MERGE_PROMPT.format(notes="\n\n".join(notes))
            + "\n\nUse this compact source context to resolve ambiguities and keep the PRD implementation-grounded:\n"
            + merge_source_context,
            None,
            max_tokens=3200,
        )
    )
    return instruction, screenshots


def description_to_text(description: Any) -> str:
    if isinstance(description, str):
        return description.strip()
    if isinstance(description, list):
        lines = []
        for item in description:
            if isinstance(item, dict):
                task_type = str(item.get("task_type", "")).strip()
                desc = str(item.get("description", "")).strip()
                if task_type and desc:
                    lines.append(f"[{task_type}] {desc}")
                elif desc:
                    lines.append(desc)
            elif item:
                lines.append(str(item).strip())
        return "\n".join(line for line in lines if line)
    return str(description or "").strip()


def base_info(instance_id: str, task: str, task_family: str) -> dict[str, Any]:
    return {
        "instance_id": instance_id,
        "task": task,
        "task_family": task_family,
        "task_type": [],
        "description": "",
        "instruction": "",
        "src_code": [],
        "dst_code": [],
        "src_screenshot": [],
        "dst_screenshot": [],
        "input_screenshots": [],
        "input_videos": [],
        "label_modified_files": [],
        "resources": [],
        "meta": {},
    }


def ensure_api_env(prefer_vision: bool = False) -> tuple[str, str | None, str]:
    maybe_load_env()
    if prefer_vision:
        api_key = os.environ.get("VISION_OPENAI_API_KEY") or os.environ.get("OPENAI_API_KEY")
        base_url = os.environ.get("VISION_OPENAI_BASE_URL") or os.environ.get("OPENAI_BASE_URL")
        model = os.environ.get("VISION_MODEL") or os.environ.get("OPENAI_MODEL") or os.environ.get("MODEL") or "gpt-4o"
    else:
        api_key = os.environ.get("OPENAI_API_KEY") or os.environ.get("VISION_OPENAI_API_KEY")
        base_url = os.environ.get("OPENAI_BASE_URL") or os.environ.get("VISION_OPENAI_BASE_URL")
        model = os.environ.get("OPENAI_MODEL") or os.environ.get("MODEL") or "gpt-4o"
    if not api_key:
        raise ValueError("Missing API key in environment")
    return api_key, base_url, model


def write_generation_instance(
    output_root: Path,
    task: str,
    project_dir: Path,
    info: dict[str, Any],
) -> Path:
    instance_dir = output_root / project_dir.name
    if instance_dir.exists():
        shutil.rmtree(instance_dir)
    instance_dir.mkdir(parents=True, exist_ok=True)
    copy_project(project_dir, instance_dir / "dst")
    safe_write_json(instance_dir / "info.json", info)
    return instance_dir


def write_pair_instance(
    output_root: Path,
    bucket: str,
    project_dir: Path,
    src_code: list[dict[str, str]],
    dst_code: list[dict[str, str]],
    info: dict[str, Any],
) -> Path:
    instance_dir = output_root / bucket / project_dir.name
    if instance_dir.exists():
        shutil.rmtree(instance_dir)
    instance_dir.mkdir(parents=True, exist_ok=True)
    write_code_bundle_from_source(project_dir, src_code, instance_dir / "src")
    write_code_bundle_from_source(project_dir, dst_code, instance_dir / "dst")
    safe_write_json(instance_dir / "info.json", info)
    return instance_dir


def build_generation_data(project_dir: Path) -> dict[str, Any]:
    return {
        "instance_id": project_dir.name,
        "dst_code": read_code_bundle(project_dir),
        "resources": collect_resources(project_dir),
    }


def _load_literal_assignments(source_path: Path, names: set[str]) -> dict[str, Any]:
    tree = ast.parse(source_path.read_text(encoding="utf-8"))
    values: dict[str, Any] = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id in names:
                values[target.id] = ast.literal_eval(node.value)
    missing = names - values.keys()
    if missing:
        raise ValueError(f"Missing literal assignments in {source_path}: {sorted(missing)}")
    return values


def strip_markdown_fence(response_text: str) -> str:
    if "```xml" in response_text:
        return response_text.split("```xml", 1)[1].split("```", 1)[0].strip()
    if "```json" in response_text:
        return response_text.split("```json", 1)[1].split("```", 1)[0].strip()
    if "```" not in response_text:
        return response_text
    parts = response_text.split("```")
    if len(parts) < 3:
        return response_text
    fenced = parts[1].strip()
    for lang in ("xml", "XML", "json", "JSON"):
        if fenced.startswith(lang):
            return fenced[len(lang) :].strip()
    return fenced


def load_edit_catalog() -> tuple[list[str], dict[str, str]]:
    values = _load_literal_assignments(
        WEB_CODING_DEMO_ROOT / "synthetic" / "edit.py",
        {"COMPLEX_COMPONENTS", "FRONTEND_BACKEND", "ADVANCED_ANIMATIONS", "BUSINESS_SCENARIOS", "TASK_DESCRIPTIONS"},
    )
    tasks = (
        values["COMPLEX_COMPONENTS"]
        + values["FRONTEND_BACKEND"]
        + values["ADVANCED_ANIMATIONS"]
        + values["BUSINESS_SCENARIOS"]
    )
    return list(tasks), dict(values["TASK_DESCRIPTIONS"])


def load_repair_catalog() -> tuple[list[str], dict[str, str]]:
    values = _load_literal_assignments(
        WEB_CODING_DEMO_ROOT / "synthetic" / "repair.py",
        {"DEFECT_TYPES", "DEFECT_DESCRIPTIONS"},
    )
    return list(values["DEFECT_TYPES"]), dict(values["DEFECT_DESCRIPTIONS"])


def apply_search_replace_local(
    code_list: list[dict[str, str]], modified_files: list[dict[str, str]], strict_mode: bool = True
) -> tuple[list[dict[str, str]], list[dict[str, Any]]]:
    """Local copy of web_coding_demo.utils.apply_search_replace without heavyweight image deps."""
    result_code = []
    code_map = {item["path"]: item["code"] for item in code_list}
    errors: list[dict[str, Any]] = []
    blocks_by_path: dict[str, list[dict[str, str]]] = {}
    for block in modified_files:
        blocks_by_path.setdefault(block["path"], []).append(block)

    for path, blocks in blocks_by_path.items():
        if path not in code_map:
            if blocks and blocks[0]["search"] == "":
                code_map[path] = ""
            else:
                error_msg = f"File path not found in code_list: {path}"
                if strict_mode:
                    raise ValueError(error_msg)
                errors.extend(
                    {"path": path, "block_index": idx, "error_type": "path_not_found", "error": error_msg}
                    for idx, _ in enumerate(blocks)
                )
                continue

        code = code_map[path]
        for block_idx, block in enumerate(blocks):
            search_text = block["search"]
            replace_text = block["replace"]
            if search_text.strip() == replace_text.strip():
                error_msg = f"Search and replace are identical in {path} (block {block_idx})."
                if strict_mode:
                    raise ValueError(error_msg)
                errors.append(
                    {
                        "path": path,
                        "block_index": block_idx,
                        "error_type": "identical_search_replace",
                        "error": error_msg,
                    }
                )
                continue
            if search_text == "" and code == "":
                code = replace_text
            elif search_text in code:
                code = code.replace(search_text, replace_text, 1)
            else:
                error_msg = (
                    f"Failed to apply search/replace in {path} (block {block_idx}).\n"
                    f"Search text (first 200 chars): {search_text[:200]}...\n"
                    "This may indicate LLM generated invalid modifications."
                )
                if strict_mode:
                    raise ValueError(error_msg)
                errors.append(
                    {"path": path, "block_index": block_idx, "error_type": "search_not_found", "error": error_msg}
                )
                continue
        code_map[path] = code

    existing_paths = {item["path"] for item in code_list}
    for item in code_list:
        new_item = item.copy()
        if item["path"] in code_map:
            new_item["code"] = code_map[item["path"]]
        result_code.append(new_item)
    for path, content in code_map.items():
        if path not in existing_paths:
            result_code.append({"path": path, "code": content})
    return result_code, errors


class LocalSearchReplaceSynthesizer:
    """Dependency-light adapter for web_coding_demo.synthetic.synthesizer.BaseSynthesizer."""

    def __init__(
        self,
        api_key: str,
        base_url: str | None = None,
        model: str = "gpt-4o",
        max_tokens: int = 8192,
        max_retries: int = 3,
    ):
        from openai import OpenAI

        self.client = OpenAI(api_key=api_key, base_url=base_url, timeout=120.0)
        self.model = model
        self.max_tokens = max_tokens
        self.max_retries = max_retries

    def format_code_context(self, code_list: list[dict[str, str]], max_chars: int = 14000) -> str:
        context = "<code_context>\n"
        remaining = max_chars
        priority = {".html": 0, ".htm": 0, ".css": 1, ".js": 2, ".jsx": 2, ".ts": 2, ".tsx": 2}
        ordered = sorted(code_list, key=lambda item: (priority.get(Path(item["path"]).suffix.lower(), 9), item["path"]))
        for item in ordered:
            if remaining <= 0:
                break
            suffix = Path(item["path"]).suffix.lower()
            per_file_limit = 4500 if suffix in {".html", ".htm"} else 3000
            code = _truncate_text(item["code"], min(remaining, per_file_limit))
            context += f'<file path="{item["path"]}">\n{code}\n</file>\n'
            remaining -= len(code)
        context += "</code_context>"
        return context

    def parse_llm_response(self, response_text: str) -> dict[str, Any]:
        response_text = strip_markdown_fence(response_text)
        desc_match = re.search(r"<description>(.*?)</description>", response_text, re.DOTALL)
        if not desc_match:
            raise ValueError("No <description> tag found in LLM response")
        description = json.loads(desc_match.group(1).strip())

        sr_matches = re.findall(
            r'<search_replace\s+path="([^"]+)">\s*<search>(.*?)</search>\s*<replace>(.*?)</replace>\s*</search_replace>',
            response_text,
            re.DOTALL,
        )
        modified_files = []
        for path, search, replace in sr_matches:
            search_stripped = search.strip()
            replace_stripped = replace.strip()
            if search_stripped == replace_stripped:
                continue
            modified_files.append(
                {"path": path.strip(), "search": search_stripped, "replace": replace_stripped}
            )
        return {"description": description, "modified_files": modified_files}

    def _validate_task_types(self, description: list[dict[str, Any]], expected_task_types: list[str] | None = None) -> None:
        if not expected_task_types:
            return
        actual_task_types = []
        for idx, item in enumerate(description):
            task_type = item.get("task_type")
            if not task_type:
                raise ValueError(f"Missing task_type at index {idx}: {item}")
            actual_task_types.append(task_type)
        if len(actual_task_types) != len(expected_task_types):
            raise ValueError(
                f"Task type count mismatch: got {len(actual_task_types)}, expected {len(expected_task_types)}"
            )
        if Counter(actual_task_types) != Counter(expected_task_types):
            raise ValueError(f"Task types do not match expected list. got={actual_task_types}, expected={expected_task_types}")

    def _generate_and_apply_with_retry(
        self,
        messages: list[dict[str, Any]],
        code_list: list[dict[str, str]],
        max_retries: int = 3,
        backoff_base: int = 2,
        expected_task_types: list[str] | None = None,
    ) -> dict[str, Any]:
        last_error: Exception | None = None
        all_attempts = []
        for attempt in range(1, max_retries + 1):
            attempt_record = {"attempt": attempt, "raw_response": None, "success": False, "error": None, "stage": None}
            try:
                attempt_record["stage"] = "llm_call"
                response = self.client.chat.completions.create(
                    model=self.model,
                    messages=messages,
                    max_tokens=self.max_tokens,
                )
                response_text = response.choices[0].message.content if response and response.choices else None
                if not response_text:
                    raise ValueError("Empty response content from LLM.")
                print(f"LLM Response (Attempt {attempt})")
                attempt_record["raw_response"] = response_text

                attempt_record["stage"] = "parse"
                parsed = self.parse_llm_response(response_text)
                if not parsed.get("modified_files"):
                    raise ValueError("Parsed LLM response has no modified_files.")

                attempt_record["stage"] = "validate_task_types"
                self._validate_task_types(parsed.get("description", []), expected_task_types)

                attempt_record["stage"] = "apply"
                modified_code, _ = apply_search_replace_local(code_list, parsed["modified_files"])

                attempt_record["success"] = True
                all_attempts.append(attempt_record)
                return {
                    "description": parsed["description"],
                    "modified_files": parsed["modified_files"],
                    "modified_code": modified_code,
                    "raw_response": response_text,
                    "llm_metadata": {
                        "model": self.model,
                        "total_attempts": attempt,
                        "all_attempts": all_attempts,
                    },
                }
            except Exception as exc:
                last_error = exc
                attempt_record["error"] = str(exc)
                all_attempts.append(attempt_record)
                if attempt == max_retries:
                    snippet = attempt_record["raw_response"]
                    if snippet and len(snippet) > 200:
                        snippet = snippet[:200] + "..."
                    print(
                        f"Generation and application failed after {attempt} attempts. "
                        f"Last error at stage '{attempt_record['stage']}': {exc}\n"
                        f"Last raw response snippet: {snippet}"
                    )
                    raise Exception(f"Failed after {max_retries} attempts. Last error: {exc}") from last_error
                wait_time = backoff_base**attempt
                print(f"Attempt {attempt}/{max_retries} failed at stage '{attempt_record['stage']}': {exc}. Retrying in {wait_time}s...")
                time.sleep(wait_time)
        raise last_error or RuntimeError("Unknown synthesis failure")


def build_forward_edit_synthesizer(api_key: str, base_url: str | None, model: str, max_retries: int = 3):
    _, task_descriptions = load_edit_catalog()

    class ForwardEditPairSynthesizer(LocalSearchReplaceSynthesizer):
        def generate_forward_pair(self, generation_data: dict[str, Any], task_types: list[str]) -> dict[str, Any]:
            src_code = generation_data["dst_code"]
            src_code_context = self.format_code_context(src_code)
            task_descriptions_str = ""
            for idx, task_type in enumerate(task_types, 1):
                task_descriptions_str += f"Task {idx}: {task_type}\n  Guideline: {task_descriptions[task_type]}\n\n"
            task_types_json = json.dumps(task_types, ensure_ascii=False)
            prompt = f"""You are an expert web developer creating high-quality web editing benchmark pairs.

I have an existing webpage codebase. Based on this code, generate {len(task_types)} context-aware editing request(s), and then implement all requested edits using strict search/replace blocks.

Tasks to implement:
{task_descriptions_str}

IMPORTANT GUIDELINES:
1. Each request must fit the website's existing theme, structure, and assets.
2. The request must describe user-facing behavior and visible outcomes, not low-level implementation details.
3. The edits must be substantial but realistic for the current repository.
4. Do not invent missing pages or external services that the current project cannot support.
5. The search text must come exactly from the current code and match uniquely.
6. Keep the implementation compact: prefer one or two focused edits in files shown below rather than broad rewrites.

Return XML with:
<description>
[
  {{"task_type": "ExactTaskType", "description": "Concrete editing request"}}
]
</description>
<search_replace path="path/to/file">
<search>
exact source text
</search>
<replace>
edited target text
</replace>
</search_replace>

**CRITICAL - task_type MUST be EXACTLY one of these values (copy verbatim):**
{task_types_json}

Your response is invalid unless it contains BOTH the <description> block and at least one <search_replace path="..."> block.
Do not stop after writing requirements. Do not say the code should be changed later. Implement the change in the same response.

Here is the existing source code to edit:
{src_code_context}"""

            result = self._generate_and_apply_with_retry(
                messages=[
                    {
                        "role": "system",
                        "content": "You generate web editing benchmark pairs in XML using exact search/replace edits.",
                    },
                    {"role": "user", "content": prompt},
                ],
                code_list=src_code,
                max_retries=self.max_retries,
                expected_task_types=task_types,
            )
            return {
                "task": "edit",
                "task_type": task_types,
                "description": result["description"],
                "src_code": src_code,
                "dst_code": result["modified_code"],
                "resources": generation_data.get("resources", []),
                "label_modified_files": result.get("modified_files", []),
                "synthetic_modified_files": result.get("modified_files", []),
                "llm_raw_response": result.get("raw_response"),
                "llm_metadata": result.get("llm_metadata"),
            }

        def process_single_generation_entry(self, *args, **kwargs) -> list[dict[str, Any]]:
            raise NotImplementedError

    return ForwardEditPairSynthesizer(api_key, base_url, model, max_tokens=4_096, max_retries=max_retries)


def build_repair_synthesizer(api_key: str, base_url: str | None, model: str, max_retries: int = 3):
    _, defect_descriptions = load_repair_catalog()

    class RepairPairSynthesizer(LocalSearchReplaceSynthesizer):
        def generate_defect_task(self, generation_data: dict[str, Any], defect_types: list[str]) -> dict[str, Any]:
            dst_code = generation_data["dst_code"]
            dst_code_context = self.format_code_context(dst_code)
            defect_descriptions_str = ""
            for idx, defect_type in enumerate(defect_types, 1):
                defect_descriptions_str += f"Defect {idx}: {defect_type}\n  Guideline: {defect_descriptions[defect_type]}\n\n"
            defect_types_json = json.dumps(defect_types, ensure_ascii=False)
            prompt = f"""You are an expert web developer. I have a clean, high-quality codebase for a webpage.
I want to generate a dataset for web repair/debugging tasks.

You need to inject {len(defect_types)} defect(s) in total:

{defect_descriptions_str}

Please analyze the provided code and inject specific defects for EACH defect type listed above.
The defects should be realistic and something that could occur during development.
Then, implement ALL the defect injections using search/replace blocks.

Return XML format with the following structure:
<description>
[
  {{"task_type": "ExactDefectTypeName1", "description": "Description for Defect 1"}},
  {{"task_type": "ExactDefectTypeName2", "description": "Description for Defect 2"}}
]
</description>
<search_replace path="path/to/file">
<search>
exact text to find in the original file
</search>
<replace>
replacement text with the defect injected
</replace>
</search_replace>

**CRITICAL - task_type values MUST be EXACTLY from this list (copy verbatim, preserve exact spelling and case):**
{defect_types_json}

Your response is invalid unless it contains BOTH the <description> block and at least one <search_replace path="..."> block.
Do not stop after describing the defects. Inject the defects in the same response.

Do NOT use:
- Placeholder names like "Defect Type 1", "Task Type 2", "Type 1"
- Synonyms or variations (e.g., "Z-Index Issue" instead of "Occlusion")
- Different capitalization (e.g., "occlusion" instead of "Occlusion")

Each task_type in your response MUST exactly match one of the defect types listed above.

Important for <description>:
- Provide a JSON array with ONE object for EACH defect (total {len(defect_types)} objects).
- Each object must have exactly two fields: "task_type" and "description".
- The "description" must be a repair instruction that clearly identifies the issue or target element.
- Do not reveal exact code implementation details such as class names, IDs, or exact CSS property values unless they are visible content.

Important for <search_replace>:
- You MUST implement defect injections for ALL {len(defect_types)} defect types.
- The <search> block must contain the EXACT text from the original file.
- The <search> text MUST be unique and match exactly once in the file.
- One <search_replace> block can only contain one pair of <search> and <replace>.
- Keep the injection compact: prefer one focused defect edit in files shown below.

Here is the clean code (which will be the Goal/Dst state after repair):
{dst_code_context}"""
            result = self._generate_and_apply_with_retry(
                messages=[
                    {
                        "role": "system",
                        "content": "You are a helpful assistant that generates web development debugging datasets in XML format using search/replace blocks.",
                    },
                    {"role": "user", "content": prompt},
                ],
                code_list=dst_code,
                max_retries=self.max_retries,
                expected_task_types=defect_types,
            )
            src_code = result["modified_code"]
            label_modified_files = [
                {"path": mod["path"], "search": mod["replace"], "replace": mod["search"]}
                for mod in result.get("modified_files", [])
            ]
            return {
                "task": "repair",
                "task_type": defect_types,
                "description": result["description"],
                "src_code": src_code,
                "dst_code": dst_code,
                "resources": generation_data.get("resources", []),
                "label_modified_files": label_modified_files,
                "synthetic_modified_files": result.get("modified_files", []),
                "llm_raw_response": result.get("raw_response"),
                "llm_metadata": result.get("llm_metadata"),
            }

    return RepairPairSynthesizer(api_key, base_url, model, max_tokens=4_096, max_retries=max_retries)
